import { cronJobs, anyApi } from "convex/server";
import { internal } from "./_generated/api";

const crons = cronJobs();

crons.interval("expire transient UI snapshots", { minutes: 10 }, internal.cleanup.transient, {});

// Ask the search service whether it is actually up and record what comes
// back (convex/health.ts's `probeSearch`). This is the only way the
// separately owned search service ever gets a health row: it does not call
// us, so nobody else can observe it.
//
// Two minutes, deliberately well under convex/summary.ts's
// SERVICE_STALE_AFTER_MS (5 minutes): a service that is genuinely up must
// never read "stale" merely because our own check runs too rarely.
//
// `anyApi` rather than the generated `internal` for the same reason
// convex/publication.ts uses it — convex/_generated/api.d.ts is a build
// artifact regenerated by `npx convex dev`/`convex codegen` and does not
// know about convex/health.ts yet. It resolves to the same function
// reference at runtime.
crons.interval("probe search service health", { minutes: 2 }, anyApi.health.probeSearch, {});

// Refill the home page's popular-posts wall (convex/wall.ts). Hourly: likes
// move slowly and the wall is decoration, not a live feed.
crons.interval("refresh home page wall", { minutes: 60 }, internal.wall.refresh, {});

export default crons;
