import { v } from "convex/values";
import { anyApi } from "convex/server";
import { httpAction, internalAction, internalMutation } from "./_generated/server";
import { serviceValidator } from "./schema";

/**
 * The write side of `serviceHealth` (convex/schema.ts): the one place that
 * turns an *observation* of a service working (or not) into a row.
 * convex/summary.ts's `health` query reads those rows and is not touched by
 * this module.
 *
 * The distinction this file exists to protect — to-do.md "Report
 * worker/indexer health and last successful activity separately from
 * 'configured'":
 *
 *   - convex/integrations.ts's `configured` answers "is an environment
 *     variable set". That is a deployment fact, not a liveness fact.
 *   - every row written here answers "was this service seen working, and
 *     when". `healthy: true` is only ever written from a real, completed
 *     observation: an HTTP response we actually read, a probe that actually
 *     came back `ok`, an import pass that actually finished. Nothing here
 *     ever derives health from configuration, and nothing seeds a row at
 *     deploy time — a service that has never reported keeps reading
 *     "unknown" in the dashboard, which is the honest answer.
 *
 * Three writers feed this, all of them reporting something they watched
 * happen:
 *
 *   1. `POST /service/health` (convex/http.ts) — an out-of-process service
 *      reporting its own liveness. Today that is Pronsh's Rust indexer
 *      (search/crates/indexer/src/health.rs), once per poll pass.
 *   2. `probeSearch` — a cron (convex/crons.ts) that asks the search
 *      service's own `/health` endpoint and records what came back.
 *   3. `convex/worker.ts`'s `poll` — the production download worker
 *      forwarding the loopback capture receiver's liveness, which it
 *      already measures on every poll.
 *
 * Auth follows the pattern convex/publication.ts established (which in turn
 * mirrors convex/lib/serviceAuth.ts): an isolated capability token with an
 * explicit legacy fallback to the shared `DATA_SERVICE_TOKEN`, never
 * borrowing another capability's credential. `anyApi.health.record` is used
 * instead of the generated `internal.health.record` for the same reason
 * convex/publication.ts does: `convex/_generated/api.d.ts` is a build
 * artifact regenerated by `npx convex dev`/`convex codegen` (both of which
 * talk to the deployment) and does not know about this module yet. It
 * resolves to the exact same function reference at runtime.
 */

// --- Auth ---------------------------------------------------------------
// A local, narrower copy of convex/lib/serviceAuth.ts's shape, exactly as
// convex/publication.ts keeps one: serviceAuth.ts's `capability` union is
// not this unit's file to widen, and health reporting is its own capability
// (a credential that may write a heartbeat must not also be able to read
// the corpus or push captures).

function healthServiceToken(env: Record<string, string | undefined> = process.env) {
  return env.SERVICE_HEALTH_TOKEN ?? env.DATA_SERVICE_TOKEN;
}

// Duplicated from convex/publication.ts rather than imported: that module
// does not export these, and it is not one of this unit's owned files.
// Same shape on purpose — one convention, two copies, not two conventions.
function bearerToken(request: Request): string | undefined {
  const header = request.headers.get("Authorization");
  if (!header) return undefined;
  const [scheme, ...rest] = header.split(" ");
  return scheme === "Bearer" && rest.length > 0 ? rest.join(" ") : undefined;
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

// --- Inbound report narrowing --------------------------------------------
// `await request.json()` is `unknown`; narrow every field by hand and fail
// closed with 400 on anything that doesn't match, per
// convex/_generated/ai/guidelines.md ("Http endpoint syntax"). An unlisted
// key is rejected too: `record` below takes a strict Convex object
// validator that throws on a key it wasn't told about, and an uncaught
// throw is a 500, not the documented 400.

type HealthReport = {
  version: 1;
  service: "indexer" | "receiver" | "search";
  healthy: boolean;
  observedAt: number;
  error?: { message: string };
};

const REPORT_KEYS = new Set(["version", "service", "healthy", "observedAt", "error"]);
const ERROR_KEYS = new Set(["message"]);
const SERVICES = new Set(["indexer", "receiver", "search"]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(value: Record<string, unknown>, allowed: Set<string>): boolean {
  return Object.keys(value).every((key) => allowed.has(key));
}

// Long enough for a real provider/transport message, short enough that a
// runaway stack trace cannot turn one row into a document-size problem.
// Truncation is marked, never silent — see `clamp` below.
const MAX_ERROR_MESSAGE = 1_000;

function clamp(message: string): string {
  return message.length <= MAX_ERROR_MESSAGE
    ? message
    : `${message.slice(0, MAX_ERROR_MESSAGE)}… (truncated)`;
}

function parseReport(body: unknown): HealthReport | null {
  if (!isRecord(body)) return null;
  if (!hasOnlyKeys(body, REPORT_KEYS)) return null;
  if (body.version !== 1) return null;
  if (typeof body.service !== "string" || !SERVICES.has(body.service)) return null;
  if (typeof body.healthy !== "boolean") return null;
  if (typeof body.observedAt !== "number" || !Number.isFinite(body.observedAt)) return null;
  if (body.error !== undefined) {
    if (!isRecord(body.error)) return null;
    if (!hasOnlyKeys(body.error, ERROR_KEYS)) return null;
    if (typeof body.error.message !== "string" || body.error.message.length === 0) return null;
    if (body.error.message.length > MAX_ERROR_MESSAGE) return null;
  }
  // An unhealthy report with nothing to say about why is not a usable
  // observation: `lastError` is supposed to carry the real failure text, so
  // a report that withholds it is rejected instead of silently storing a
  // bare `healthy: false` the dashboard cannot explain.
  if (!body.healthy && body.error === undefined) return null;
  return body as HealthReport;
}

// --- HTTP entry point -----------------------------------------------------

export const receiveReport = httpAction(async (ctx, request) => {
  // Rejected at the transport layer, before the body is read, exactly like
  // convex/publication.ts's receiver. A missing token configuration fails
  // CLOSED: an unconfigured receiver is never an open one.
  const expected = healthServiceToken();
  if (!expected || bearerToken(request) !== expected) {
    return json({ outcome: "rejected_unauthorized" }, 401);
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return json({ error: "Request body must be JSON." }, 400);
  }

  const report = parseReport(body);
  if (!report) {
    return json(
      {
        error:
          "Request body must be { version: 1, service, healthy, observedAt, error? }, " +
          "with an error message whenever healthy is false.",
      },
      400,
    );
  }

  await ctx.runMutation(anyApi.health.record, {
    service: report.service,
    healthy: report.healthy,
    // The reporter's own account of when it saw the failure, kept verbatim
    // alongside its message. The row's own `observedAt` is stamped by the
    // deployment (see `record`), so a skewed remote clock can never make a
    // reading look fresher than it is.
    error: report.error
      ? { message: report.error.message, observedAt: report.observedAt }
      : undefined,
  });
  return json({ recorded: true }, 200);
});

// --- The upsert -----------------------------------------------------------

export const record = internalMutation({
  args: {
    service: serviceValidator,
    healthy: v.boolean(),
    error: v.optional(v.object({ message: v.string(), observedAt: v.number() })),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    // Deliberately the deployment's own clock, not the reporter's: this
    // timestamp is what convex/summary.ts compares against `now` to decide
    // "stale", and staleness must not be forgeable or skewable by whoever
    // is reporting. It is the time we recorded an observation that had just
    // been made, which is what the dashboard means by "last seen".
    const observedAt = Date.now();
    const existing = await ctx.db
      .query("serviceHealth")
      .withIndex("by_service", (q) => q.eq("service", args.service))
      // `.first()`, not `.unique()`: by_service is an ordinary index with no
      // uniqueness guarantee, so a duplicate row would throw and take the
      // whole query down rather than degrade one reading.
      .first();

    // One row per service, forever: patch when it exists, insert only the
    // first time. A history of readings is not what this table is for — the
    // dashboard asks "is it alive now, and when did it last work".
    const doc: {
      service: "indexer" | "receiver" | "search";
      healthy: boolean;
      observedAt: number;
      lastHeartbeatAt: number;
      lastSuccessAt?: number;
      lastError?: { message: string; observedAt: number };
    } = {
      service: args.service,
      healthy: args.healthy,
      observedAt,
      // "We got a report about this service at this time." Every writer
      // here reports synchronously at the moment of observation, so this
      // equals `observedAt` today; the schema keeps them separate for a
      // future writer that forwards an older heartbeat it was holding.
      lastHeartbeatAt: observedAt,
    };

    // The two sticky fields, following the same rule convex/publication.ts
    // uses for `searchablePostCount`/`lastError`: each is written only by
    // the kind of report that can actually establish it, and is NEVER
    // cleared by the other kind.
    //
    //   - `lastSuccessAt` moves only on an observed success, so a failure
    //     cannot erase the evidence that the service worked at 14:02.
    //   - `lastError` keeps the last real failure text, so a later success
    //     does not erase what went wrong. It is timestamped independently,
    //     and `healthy` (plus the row's own `observedAt`) is what says
    //     whether that error is the current state or history.
    if (args.healthy) doc.lastSuccessAt = observedAt;
    if (args.error)
      doc.lastError = { message: clamp(args.error.message), observedAt: args.error.observedAt };

    if (existing) await ctx.db.patch(existing._id, doc);
    else await ctx.db.insert("serviceHealth", doc);
    return null;
  },
});

// --- Search-service probe (convex/crons.ts) -------------------------------

// The search service answers `GET /health` with this exact body (verified
// against the running service on this VM). Checking the body and not just
// the status keeps a proxy's own 200 from being mistaken for the service
// being up.
const SEARCH_HEALTH_BODY = "ok";
const SEARCH_PROBE_TIMEOUT_MS = 10_000;
// A body snippet long enough to identify what answered instead (an error
// page's first line, a proxy banner) without storing a whole document.
const BODY_SNIPPET = 200;

/**
 * Derive the health URL from `SEARCH_API_URL` rather than hardcoding a host:
 * the search service is separately owned and moves. `SEARCH_API_URL` is the
 * retrieval endpoint (a path on that service); `/health` is a sibling at the
 * same origin, port included.
 */
export function searchHealthUrl(configured: string): string | null {
  try {
    return new URL("/health", configured).toString();
  } catch {
    return null;
  }
}

export const probeSearch = internalAction({
  args: {},
  returns: v.null(),
  handler: async (ctx): Promise<null> => {
    const configured = process.env.SEARCH_API_URL;
    // Not configured means we have nowhere to look, which is not the same
    // as the service being down. Record nothing: the dashboard keeps saying
    // "no health report received yet", which is exactly true.
    if (!configured) return null;
    const url = searchHealthUrl(configured);
    if (!url) {
      // Same reasoning: a URL we cannot even parse is a fact about our
      // configuration, not an observation of the service. Logged, not
      // recorded as `healthy: false` — that would blame the service for our
      // own misconfiguration.
      console.error("health probe: SEARCH_API_URL is not a valid URL; no health recorded.");
      return null;
    }

    let failure: string | undefined;
    try {
      const response = await fetch(url, {
        method: "GET",
        redirect: "error",
        signal: AbortSignal.timeout(SEARCH_PROBE_TIMEOUT_MS),
      });
      if (response.ok) {
        const body = (await response.text()).trim();
        if (body !== SEARCH_HEALTH_BODY)
          failure = `Search health check answered ${response.status} with an unexpected body: ${body.slice(0, BODY_SNIPPET)}`;
      } else {
        failure = `Search health check answered HTTP ${response.status}.`;
      }
    } catch (error) {
      // The transport's own words — a DNS/connect/TLS/timeout message —
      // stored as-is rather than rewritten into a friendlier sentence that
      // would hide which of those it was.
      failure = error instanceof Error ? error.message : String(error);
    }

    await ctx.runMutation(anyApi.health.record, {
      service: "search",
      // Only ever true because a response was received AND said `ok`.
      healthy: failure === undefined,
      error: failure === undefined ? undefined : { message: failure, observedAt: Date.now() },
    });
    return null;
  },
});
