import { z } from "zod";
import { v } from "convex/values";
import { anyApi } from "convex/server";
import { httpAction, internalMutation } from "./_generated/server";
import type { MutationCtx } from "./_generated/server";
import type { Id } from "./_generated/dataModel";
import { publicationUpdateOutcomeValidator } from "./schema";
import { publicationUpdateEnvelope, type PublicationUpdateEnvelope } from "./lib/contracts";
import { resolveAccount } from "./lib/accounts";

/**
 * The Convex-side receiver for Pronsh's publication-update contract:
 * docs/publication-contract.md, built on the frozen shapes in
 * convex/schema.ts and convex/lib/contracts.ts. This file owns exactly the
 * boundary between "the indexer told us something" and "accountPublications
 * reflects it" — it does NOT implement, and must never grow into, any part
 * of the sender/watcher/registry/retry-loop that stays on Pronsh's side.
 *
 * Two things worth calling out for whoever wires this up further:
 *
 * 1. Auth follows the *pattern* already established in
 *    convex/lib/serviceAuth.ts (an isolated capability token with an
 *    explicit legacy fallback, never borrowing another capability's
 *    credential) without editing that file: docs/publication-contract.md's
 *    "Delivery" section proposes a third `"publication"` capability there
 *    for a later unit to add. Until then, `publicationServiceToken` below
 *    is a local, narrower copy of the same shape.
 * 2. `applyUpdate` is called via `anyApi` (convex/server) rather than the
 *    generated `internal` object, because `convex/_generated/api.d.ts` is a
 *    build artifact regenerated by `npx convex dev`/`convex codegen` — both
 *    of which talk to the deployment — and is not one of this unit's owned
 *    files. `anyApi.publication.applyUpdate` resolves to the exact same
 *    function reference at runtime; swap it for `internal.publication.applyUpdate`
 *    once codegen has run and picked up this module.
 */

// --- Auth ---------------------------------------------------------------

function publicationServiceToken(env: Record<string, string | undefined> = process.env) {
  return env.PUBLICATION_SERVICE_TOKEN ?? env.DATA_SERVICE_TOKEN;
}

function bearerToken(request: Request): string | undefined {
  const header = request.headers.get("Authorization");

  if (!header) return undefined;
  const [scheme, ...rest] = header.split(" ");

  return scheme === "Bearer" && rest.length > 0 ? rest.join(" ") : undefined;
}

/** A JSON-serializable value — exactly what `JSON.stringify` accepts. */
type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

function json(body: JsonValue, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

// --- Same-generation replay conflict detection ----------------------------
// A resend under the SAME generation number is only a true idempotent
// replay if it reflects the exact same content as what was already applied
// — docs/publication-contract.md is explicit that a resent generation
// "must reflect the exact same content". Comparing every material field by
// hand on every duplicate would be brittle to add to, so instead a small
// digest of exactly those fields (reportedState, captureIds, uniquePostCount,
// pendingWork, error — deliberately NOT runId/observedAt/handle/
// providerAccountId, which can legitimately vary between an original send
// and a resend of the same report) is computed and stored once, on every
// applied update, and compared on the next one claiming the same generation.
//
// A non-cryptographic hash (FNV-1a) is enough here: this is integrity
// detection against an accidental or buggy resend, not an adversarial
// collision search, and it avoids depending on Web Crypto's async
// SubtleCrypto API being available in every Convex runtime this mutation
// might run in.
function fnv1a(input: string): string {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

function materialDigest(args: {
  reportedState: string;
  captureIds: string[];
  uniquePostCount?: number;
  pendingWork?: { unit: string; count: number };
  error?: { message: string; code?: string };
}): string {
  // captureIds sorted before hashing: the same set of confirmed captures
  // resent in a different order is the same report, not a conflicting one.
  return fnv1a(
    JSON.stringify({
      reportedState: args.reportedState,
      captureIds: [...args.captureIds].sort(),
      uniquePostCount: args.uniquePostCount ?? null,
      pendingWork: args.pendingWork ?? null,
      error: args.error ?? null,
    }),
  );
}

// --- Inbound envelope narrowing -------------------------------------------
// `await request.json()` is `unknown`; decode it with a schema and fail
// closed with 400 on anything that doesn't match the shape, per
// convex/_generated/ai/guidelines.md ("Http endpoint syntax"). This checks
// only *shape* (right types, right literals) — contract-level rules that
// depend on more than one field (e.g. a "failed" report needing `error`)
// belong in applyUpdate below, where they can be logged as a proper
// `rejected_invalid` outcome instead of a bare 400.
//
// `.strict()` at every level rejects an unlisted key, exactly like the
// hand-rolled key-set checks this replaced. applyUpdate's `args` (below) is
// `publicationUpdateEnvelope.fields`, a strict Convex object validator that
// throws an uncaught error on any key it wasn't told about — including
// inside the nested `pendingWork`/`error` objects. Forwarding a
// well-formed-but-additive body (an extra debug field, a future envelope
// field a sender added before this receiver knows about it) straight
// through would crash the httpAction instead of failing closed with the
// documented 400.

// A count of things is a non-negative integer. Applies to uniquePostCount and
// pendingWork.count only; generation and timestamps stay finite-number checks.
const countSchema = z.number().int().min(0);

const publicationUpdateEnvelopeSchema = z
  .object({
    version: z.literal(1),
    providerAccountId: z.string().optional(),
    handle: z.string().min(1),
    runId: z.string().optional(),
    captureIds: z.array(z.string()),
    generation: z.number().finite(),
    reportedState: z.enum(["indexing", "searchable", "failed"]),
    uniquePostCount: countSchema.optional(),
    uniquePostCountAsOf: z.number().optional(),
    pendingWork: z
      .strictObject({
        unit: z.enum(["jobs", "captures", "posts"]),
        count: countSchema,
      })
      .optional(),
    error: z
      .strictObject({
        message: z.string(),
        code: z.string().optional(),
      })
      .optional(),
    observedAt: z.number().finite(),
  })
  .strict();

// --- HTTP entry point -----------------------------------------------------

export const receiveUpdate = httpAction(async (ctx, request) => {
  // Authentication failures are rejected at the transport layer, before the
  // body is even read, per docs/publication-contract.md "Idempotency and
  // staleness". A missing token configuration fails closed too: an
  // unconfigured receiver is never treated as an open one.
  const expected = publicationServiceToken();

  if (!expected || bearerToken(request) !== expected) {
    return json({ outcome: "rejected_unauthorized" }, 401);
  }

  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return json({ error: "Request body must be JSON." }, 400);
  }

  const parsed = publicationUpdateEnvelopeSchema.safeParse(body);

  if (!parsed.success)
    return json({ error: "Request body does not match publicationUpdateEnvelope." }, 400);

  const envelope: PublicationUpdateEnvelope = parsed.data;

  const result: {
    outcome: "applied" | "stale_ignored" | "duplicate_ignored" | "rejected_invalid";
    committedGeneration?: number;
    rejectionReason?: string;
  } = await ctx.runMutation(anyApi.publication.applyUpdate, envelope);

  return json(result, result.outcome === "rejected_invalid" ? 422 : 200);
});

// --- Identity resolution ----------------------------------------------------
// Delegated to convex/lib/accounts.ts so this receiver resolves an update to
// exactly the row convex/jobs.ts wrote and convex/library.ts displays.
//
// It used to resolve duplicates for one provider id as "ambiguous" and reject
// the update. Once the write path started treating such rows as one account,
// that disagreement meant an account visible in the library would have every
// publication update rejected as `rejected_invalid` — it would sit at
// "waiting for indexing" forever while the sender collected 422s.

// --- Durable audit log ------------------------------------------------------
// Every publication update is logged, accepted or not, so "duplicate
// updates are idempotent" and "stale updates cannot regress displayed
// state" are provable from evidence instead of merely asserted. See
// docs/publication-contract.md "Idempotency and staleness".
async function logUpdate(
  ctx: MutationCtx,
  args: Omit<PublicationUpdateEnvelope, "version">,
  receivedAt: number,
  accountId: Id<"accounts"> | undefined,
  outcome: "applied" | "stale_ignored" | "duplicate_ignored" | "rejected_invalid",
  rejectionReason?: string,
) {
  await ctx.db.insert("publicationUpdates", {
    providerAccountId: args.providerAccountId,
    handle: args.handle,
    runId: args.runId,
    captureIds: args.captureIds,
    generation: args.generation,
    reportedState: args.reportedState,
    uniquePostCount: args.uniquePostCount,
    uniquePostCountAsOf: args.uniquePostCountAsOf,
    pendingWork: args.pendingWork,
    error: args.error,
    observedAt: args.observedAt,
    accountId,
    receivedAt,
    outcome,
    rejectionReason,
  });
}

type AccountPublicationDoc = {
  accountId: Id<"accounts">;
  state: "indexing" | "searchable" | "failed";
  committedGeneration: number;
  updatedAt: number;
  searchablePostCount?: number;
  searchablePostCountAsOf?: number;
  lastPublishedAt?: number;
  lastError?: { message: string; observedAt: number; generation: number };
  pendingWork?: { unit: "jobs" | "captures" | "posts"; count: number };
  // A digest of this update's material fields (reportedState, captureIds,
  // uniquePostCount, pendingWork, error), recorded on every applied update
  // so a later resend claiming the SAME generation can be told apart from a
  // true idempotent replay — see `materialDigest` below.
  lastAppliedDigest: string;
};

export const applyUpdate = internalMutation({
  args: publicationUpdateEnvelope.fields,
  returns: v.object({
    outcome: publicationUpdateOutcomeValidator,
    committedGeneration: v.optional(v.number()),
    rejectionReason: v.optional(v.string()),
  }),
  handler: async (ctx, args) => {
    const receivedAt = Date.now();

    // Contract-level shape rules that span more than one field: these are
    // "rejected_invalid", not a transport-level 400, because the envelope
    // itself is well-formed — it just violates a rule this contract states
    // in prose. docs/publication-contract.md "The envelope" table.
    if (args.reportedState === "failed" && !args.error) {
      await logUpdate(
        ctx,
        args,
        receivedAt,
        undefined,
        "rejected_invalid",
        'A "failed" update must include an error.',
      );

      return {
        outcome: "rejected_invalid" as const,
        rejectionReason: 'A "failed" update must include an error.',
      };
    }

    if (args.uniquePostCount !== undefined && args.uniquePostCountAsOf === undefined) {
      const reason = "uniquePostCountAsOf is required whenever uniquePostCount is present.";
      await logUpdate(ctx, args, receivedAt, undefined, "rejected_invalid", reason);

      return { outcome: "rejected_invalid" as const, rejectionReason: reason };
    }

    // This app never creates an account row from a publication update alone
    // — accounts are created only by our own acquisition flow (jobs.finish).
    // An update that cannot resolve to an existing account is rejected, not
    // used to invent one. docs/publication-contract.md "Account identity".
    const accountId = (await resolveAccount(ctx.db, args))?._id;

    if (!accountId) {
      const reason = "No known account matches this update's providerAccountId/handle.";
      await logUpdate(ctx, args, receivedAt, undefined, "rejected_invalid", reason);

      return { outcome: "rejected_invalid" as const, rejectionReason: reason };
    }

    const existing = await ctx.db
      .query("accountPublications")
      .withIndex("by_account", (q) => q.eq("accountId", accountId))
      .unique();

    const stored = existing?.committedGeneration;
    const digest = materialDigest(args);

    // Generation-based idempotency and staleness, entirely per account.
    // docs/publication-contract.md "Idempotency and staleness". No row yet
    // means no update has ever been accepted for this account, so this one
    // always applies regardless of its numeric value.
    let outcome: "applied" | "stale_ignored" | "duplicate_ignored" | "rejected_invalid";
    let conflictReason: string | undefined;

    if (stored === undefined) outcome = "applied";
    else if (args.generation < stored) outcome = "stale_ignored";
    else if (args.generation === stored) {
      // A resend of the SAME generation must reflect the exact same
      // content to be a true no-op. When the committed row has a digest to
      // compare against (see accountPublications.lastAppliedDigest — rows
      // written before this field existed have none, and fall back to the
      // old duplicate_ignored behavior since there is nothing to compare),
      // a mismatch means two different reports claim to be the same
      // generation — a contract violation, not an idempotent replay.
      if (existing?.lastAppliedDigest !== undefined && existing.lastAppliedDigest !== digest) {
        outcome = "rejected_invalid";
        conflictReason = `conflicting replay of generation ${args.generation}`;
      } else {
        outcome = "duplicate_ignored";
      }
    } else outcome = "applied";

    if (outcome !== "applied") {
      // Never restate a different reportedState on the stored row: a
      // resent generation number must reflect the exact same content, and
      // an "idempotent replay" must be a true no-op, not a reinterpretation.
      await logUpdate(ctx, args, receivedAt, accountId, outcome, conflictReason);

      return {
        outcome,
        committedGeneration: stored,
        ...(conflictReason ? { rejectionReason: conflictReason } : {}),
      };
    }

    // Apply. `state` and `committedGeneration` always move; the sticky
    // "last known good" fields (searchablePostCount/…/lastPublishedAt) are
    // written ONLY on an accepted "searchable" report, and `lastError` only
    // on an accepted "failed" report — never cleared by any other outcome.
    // This field separation is what makes the non-regression guarantee
    // hold: docs/publication-contract.md "The non-regression guarantee".
    //
    // `pendingWork` follows the same sticky pattern as `lastError` and
    // `searchablePostCount`, but is not scoped to one `reportedState`: the
    // indexer can report outstanding work alongside *any* of
    // indexing/searchable/failed (e.g. "searchable, 0 jobs left" or "failed,
    // 3 jobs still queued for retry"), so it is written whenever the
    // envelope includes it, on any applied update. Per
    // docs/publication-contract.md's envelope table, "omit when unknown" —
    // never send a guessed count — so an update that omits `pendingWork`
    // means "this update has nothing to say about outstanding work", not
    // "there is none". The stored value is therefore left untouched (not
    // cleared) when a later applied update omits the field, exactly like
    // `lastError` is never cleared by a later success that doesn't restate
    // failure.
    const doc: AccountPublicationDoc = {
      accountId,
      state: args.reportedState,
      committedGeneration: args.generation,
      updatedAt: receivedAt,
      // Recorded on every applied update (not only when reportedState is
      // "searchable") so the very next update — of ANY reported state —
      // resent under this same generation number has something to compare
      // against.
      lastAppliedDigest: digest,
    };

    if (args.reportedState === "searchable" && args.uniquePostCount !== undefined) {
      doc.searchablePostCount = args.uniquePostCount;
      doc.searchablePostCountAsOf = args.uniquePostCountAsOf;
      doc.lastPublishedAt = receivedAt;
    }

    if (args.reportedState === "failed" && args.error) {
      doc.lastError = {
        message: args.error.message,
        observedAt: args.observedAt,
        generation: args.generation,
      };
    }

    if (args.pendingWork !== undefined) {
      doc.pendingWork = args.pendingWork;
    }

    if (existing) await ctx.db.patch(existing._id, doc);
    else await ctx.db.insert("accountPublications", doc);

    await logUpdate(ctx, args, receivedAt, accountId, "applied");

    return { outcome: "applied" as const, committedGeneration: args.generation };
  },
});
