import { v } from "convex/values";
import { anyApi } from "convex/server";
import { httpAction, internalMutation } from "./_generated/server";
import type { MutationCtx } from "./_generated/server";
import type { Id } from "./_generated/dataModel";
import { publicationUpdateOutcomeValidator } from "./schema";
import { publicationUpdateEnvelope, type PublicationUpdateEnvelope } from "./lib/contracts";

/**
 * The Convex-side receiver for Pronsh's publication-update contract:
 * docs/publication-contract.md, built on the frozen shapes in
 * convex/schema.ts and convex/lib/contracts.ts. This file owns exactly the
 * boundary between "the indexer told us something" and "accountPublications
 * reflects it" — it does NOT implement, and must never grow into, any part
 * of the sender/watcher/registry/retry-loop that stays on Pronsh's side.
 *
 * Two things worth calling out for whoever wires this up further:
 *
 * 1. Auth follows the *pattern* already established in
 *    convex/lib/serviceAuth.ts (an isolated capability token with an
 *    explicit legacy fallback, never borrowing another capability's
 *    credential) without editing that file: docs/publication-contract.md's
 *    "Delivery" section proposes a third `"publication"` capability there
 *    for a later unit to add. Until then, `publicationServiceToken` below
 *    is a local, narrower copy of the same shape.
 * 2. `applyUpdate` is called via `anyApi` (convex/server) rather than the
 *    generated `internal` object, because `convex/_generated/api.d.ts` is a
 *    build artifact regenerated by `npx convex dev`/`convex codegen` — both
 *    of which talk to the deployment — and is not one of this unit's owned
 *    files. `anyApi.publication.applyUpdate` resolves to the exact same
 *    function reference at runtime; swap it for `internal.publication.applyUpdate`
 *    once codegen has run and picked up this module.
 */

// --- Auth ---------------------------------------------------------------

function publicationServiceToken(env: Record<string, string | undefined> = process.env) {
  return env.PUBLICATION_SERVICE_TOKEN ?? env.DATA_SERVICE_TOKEN;
}

function bearerToken(request: Request): string | undefined {
  const header = request.headers.get("Authorization");
  if (!header) return undefined;
  const [scheme, ...rest] = header.split(" ");
  return scheme === "Bearer" && rest.length > 0 ? rest.join(" ") : undefined;
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

// --- Inbound envelope narrowing -------------------------------------------
// `await request.json()` is `unknown`; narrow every field by hand and fail
// closed with 400 on anything that doesn't match the shape, per
// convex/_generated/ai/guidelines.md ("Http endpoint syntax"). This checks
// only *shape* (right types, right literals) — contract-level rules that
// depend on more than one field (e.g. a "failed" report needing `error`)
// belong in applyUpdate below, where they can be logged as a proper
// `rejected_invalid` outcome instead of a bare 400.

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((entry) => typeof entry === "string");
}
// No unlisted key survives shape-checking, at any level of the envelope.
// applyUpdate's `args` (below) is `publicationUpdateEnvelope.fields`, a
// strict Convex object validator that throws an uncaught error on any key
// it wasn't told about — including inside the nested `pendingWork`/`error`
// objects. Forwarding a well-formed-but-additive body (an extra debug
// field, a future envelope field a sender added before this receiver knows
// about it) straight through would crash the httpAction instead of failing
// closed with the documented 400. Whitelisting every level here, from the
// same field list `applyUpdate` uses, is what keeps "unknown shape -> 400"
// true instead of "unknown shape -> uncaught exception".
const ENVELOPE_KEYS = new Set(Object.keys(publicationUpdateEnvelope.fields));
const PENDING_WORK_KEYS = new Set(["unit", "count"]);
const ERROR_KEYS = new Set(["message", "code"]);
function hasOnlyKeys(value: Record<string, unknown>, allowed: Set<string>): boolean {
  return Object.keys(value).every((key) => allowed.has(key));
}
const REPORTED_STATES = new Set(["indexing", "searchable", "failed"]);
const PENDING_WORK_UNITS = new Set(["jobs", "captures", "posts"]);

export // A count of things is a non-negative integer. Applies to uniquePostCount and
// pendingWork.count only; generation and timestamps stay finite-number checks.
function isCount(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 0;
}

function parseEnvelope(body: unknown): PublicationUpdateEnvelope | null {
  if (!isRecord(body)) return null;
  if (!hasOnlyKeys(body, ENVELOPE_KEYS)) return null;
  if (body.version !== 1) return null;
  if (typeof body.handle !== "string" || body.handle.length === 0) return null;
  if (!isStringArray(body.captureIds)) return null;
  if (typeof body.generation !== "number" || !Number.isFinite(body.generation)) return null;
  if (typeof body.reportedState !== "string" || !REPORTED_STATES.has(body.reportedState))
    return null;
  if (typeof body.observedAt !== "number" || !Number.isFinite(body.observedAt)) return null;
  if (body.providerAccountId !== undefined && typeof body.providerAccountId !== "string")
    return null;
  if (body.runId !== undefined && typeof body.runId !== "string") return null;
  if (body.uniquePostCount !== undefined && !isCount(body.uniquePostCount)) return null;
  if (body.uniquePostCountAsOf !== undefined && typeof body.uniquePostCountAsOf !== "number")
    return null;
  if (body.pendingWork !== undefined) {
    if (!isRecord(body.pendingWork)) return null;
    if (!hasOnlyKeys(body.pendingWork, PENDING_WORK_KEYS)) return null;
    if (typeof body.pendingWork.unit !== "string" || !PENDING_WORK_UNITS.has(body.pendingWork.unit))
      return null;
    if (!isCount(body.pendingWork.count)) return null;
  }
  if (body.error !== undefined) {
    if (!isRecord(body.error)) return null;
    if (!hasOnlyKeys(body.error, ERROR_KEYS)) return null;
    if (typeof body.error.message !== "string") return null;
    if (body.error.code !== undefined && typeof body.error.code !== "string") return null;
  }
  return body as PublicationUpdateEnvelope;
}

// --- HTTP entry point -----------------------------------------------------

export const receiveUpdate = httpAction(async (ctx, request) => {
  // Authentication failures are rejected at the transport layer, before the
  // body is even read, per docs/publication-contract.md "Idempotency and
  // staleness". A missing token configuration fails closed too: an
  // unconfigured receiver is never treated as an open one.
  const expected = publicationServiceToken();
  if (!expected || bearerToken(request) !== expected) {
    return json({ outcome: "rejected_unauthorized" }, 401);
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return json({ error: "Request body must be JSON." }, 400);
  }

  const envelope = parseEnvelope(body);
  if (!envelope) return json({ error: "Request body does not match publicationUpdateEnvelope." }, 400);

  const result: {
    outcome: "applied" | "stale_ignored" | "duplicate_ignored" | "rejected_invalid";
    committedGeneration?: number;
    rejectionReason?: string;
  } = await ctx.runMutation(anyApi.publication.applyUpdate, envelope);

  return json(result, result.outcome === "rejected_invalid" ? 422 : 200);
});

// --- Identity resolution ----------------------------------------------------
// Provider account id first, handle only as a fallback when no provider id
// was asserted at all. Deliberately does NOT fall back from a non-matching
// providerAccountId to a handle match: once an update asserts a provider id,
// honoring a handle match instead risks silently merging it into a
// different real account after a handle reassignment. See
// docs/publication-contract.md "account identity" and the frozen modeling
// decision on accounts.by_user_id being the primary identity key.
async function resolveAccountId(
  ctx: MutationCtx,
  args: { providerAccountId?: string; handle: string },
): Promise<Id<"accounts"> | undefined> {
  // Neither accounts.by_user_id nor accounts.by_handle is uniqueness-enforced
  // by the schema, so `.unique()` would THROW on a duplicated row and turn a
  // contract-level "rejected_invalid" into a 500. Read at most two and treat
  // an ambiguous match as no match, so applyUpdate can log and reject it.
  if (args.providerAccountId !== undefined) {
    const matches = await ctx.db
      .query("accounts")
      .withIndex("by_user_id", (q) => q.eq("userId", args.providerAccountId!))
      .take(2);
    return matches.length === 1 ? matches[0]._id : undefined;
  }
  const matches = await ctx.db
    .query("accounts")
    .withIndex("by_handle", (q) => q.eq("handle", args.handle))
    .take(2);
  return matches.length === 1 ? matches[0]._id : undefined;
}

// --- Durable audit log ------------------------------------------------------
// Every publication update is logged, accepted or not, so "duplicate
// updates are idempotent" and "stale updates cannot regress displayed
// state" are provable from evidence instead of merely asserted. See
// docs/publication-contract.md "Idempotency and staleness".
async function logUpdate(
  ctx: MutationCtx,
  args: Omit<PublicationUpdateEnvelope, "version">,
  receivedAt: number,
  accountId: Id<"accounts"> | undefined,
  outcome: "applied" | "stale_ignored" | "duplicate_ignored" | "rejected_invalid",
  rejectionReason?: string,
) {
  await ctx.db.insert("publicationUpdates", {
    providerAccountId: args.providerAccountId,
    handle: args.handle,
    runId: args.runId,
    captureIds: args.captureIds,
    generation: args.generation,
    reportedState: args.reportedState,
    uniquePostCount: args.uniquePostCount,
    uniquePostCountAsOf: args.uniquePostCountAsOf,
    pendingWork: args.pendingWork,
    error: args.error,
    observedAt: args.observedAt,
    accountId,
    receivedAt,
    outcome,
    rejectionReason,
  });
}

export const applyUpdate = internalMutation({
  args: publicationUpdateEnvelope.fields,
  returns: v.object({
    outcome: publicationUpdateOutcomeValidator,
    committedGeneration: v.optional(v.number()),
    rejectionReason: v.optional(v.string()),
  }),
  handler: async (ctx, args) => {
    const receivedAt = Date.now();

    // Contract-level shape rules that span more than one field: these are
    // "rejected_invalid", not a transport-level 400, because the envelope
    // itself is well-formed — it just violates a rule this contract states
    // in prose. docs/publication-contract.md "The envelope" table.
    if (args.reportedState === "failed" && !args.error) {
      await logUpdate(
        ctx,
        args,
        receivedAt,
        undefined,
        "rejected_invalid",
        "A \"failed\" update must include an error.",
      );
      return { outcome: "rejected_invalid" as const, rejectionReason: "A \"failed\" update must include an error." };
    }
    if (args.uniquePostCount !== undefined && args.uniquePostCountAsOf === undefined) {
      const reason = "uniquePostCountAsOf is required whenever uniquePostCount is present.";
      await logUpdate(ctx, args, receivedAt, undefined, "rejected_invalid", reason);
      return { outcome: "rejected_invalid" as const, rejectionReason: reason };
    }

    // This app never creates an account row from a publication update alone
    // — accounts are created only by our own acquisition flow (jobs.finish).
    // An update that cannot resolve to an existing account is rejected, not
    // used to invent one. docs/publication-contract.md "Account identity".
    const accountId = await resolveAccountId(ctx, args);
    if (!accountId) {
      const reason = "No known account matches this update's providerAccountId/handle.";
      await logUpdate(ctx, args, receivedAt, undefined, "rejected_invalid", reason);
      return { outcome: "rejected_invalid" as const, rejectionReason: reason };
    }

    const existing = await ctx.db
      .query("accountPublications")
      .withIndex("by_account", (q) => q.eq("accountId", accountId))
      .unique();
    const stored = existing?.committedGeneration;

    // Generation-based idempotency and staleness, entirely per account.
    // docs/publication-contract.md "Idempotency and staleness". No row yet
    // means no update has ever been accepted for this account, so this one
    // always applies regardless of its numeric value.
    let outcome: "applied" | "stale_ignored" | "duplicate_ignored";
    if (stored === undefined) outcome = "applied";
    else if (args.generation < stored) outcome = "stale_ignored";
    else if (args.generation === stored) outcome = "duplicate_ignored";
    else outcome = "applied";

    if (outcome !== "applied") {
      // Never restate a different reportedState on the stored row: a
      // resent generation number must reflect the exact same content, and
      // an "idempotent replay" must be a true no-op, not a reinterpretation.
      await logUpdate(ctx, args, receivedAt, accountId, outcome);
      return { outcome, committedGeneration: stored };
    }

    // Apply. `state` and `committedGeneration` always move; the sticky
    // "last known good" fields (searchablePostCount/…/lastPublishedAt) are
    // written ONLY on an accepted "searchable" report, and `lastError` only
    // on an accepted "failed" report — never cleared by any other outcome.
    // This field separation is what makes the non-regression guarantee
    // hold: docs/publication-contract.md "The non-regression guarantee".
    //
    // `pendingWork` follows the same sticky pattern as `lastError` and
    // `searchablePostCount`, but is not scoped to one `reportedState`: the
    // indexer can report outstanding work alongside *any* of
    // indexing/searchable/failed (e.g. "searchable, 0 jobs left" or "failed,
    // 3 jobs still queued for retry"), so it is written whenever the
    // envelope includes it, on any applied update. Per
    // docs/publication-contract.md's envelope table, "omit when unknown" —
    // never send a guessed count — so an update that omits `pendingWork`
    // means "this update has nothing to say about outstanding work", not
    // "there is none". The stored value is therefore left untouched (not
    // cleared) when a later applied update omits the field, exactly like
    // `lastError` is never cleared by a later success that doesn't restate
    // failure.
    const doc: {
      accountId: Id<"accounts">;
      state: "indexing" | "searchable" | "failed";
      committedGeneration: number;
      updatedAt: number;
      searchablePostCount?: number;
      searchablePostCountAsOf?: number;
      lastPublishedAt?: number;
      lastError?: { message: string; observedAt: number; generation: number };
      pendingWork?: { unit: "jobs" | "captures" | "posts"; count: number };
    } = {
      accountId,
      state: args.reportedState,
      committedGeneration: args.generation,
      updatedAt: receivedAt,
    };
    if (args.reportedState === "searchable" && args.uniquePostCount !== undefined) {
      doc.searchablePostCount = args.uniquePostCount;
      doc.searchablePostCountAsOf = args.uniquePostCountAsOf;
      doc.lastPublishedAt = receivedAt;
    }
    if (args.reportedState === "failed" && args.error) {
      doc.lastError = {
        message: args.error.message,
        observedAt: args.observedAt,
        generation: args.generation,
      };
    }
    if (args.pendingWork !== undefined) {
      doc.pendingWork = args.pendingWork;
    }
    if (existing) await ctx.db.patch(existing._id, doc);
    else await ctx.db.insert("accountPublications", doc);

    await logUpdate(ctx, args, receivedAt, accountId, "applied");
    return { outcome: "applied" as const, committedGeneration: args.generation };
  },
});
