import { action, internalMutation } from "./_generated/server";
import { internal } from "./_generated/api";
// `anyApi.health.record` rather than `internal.health.record`: convex/
// _generated/api.d.ts is a build artifact regenerated by `npx convex dev`/
// `convex codegen` and does not know about convex/health.ts yet. Same
// function reference at runtime — see convex/publication.ts's header.
import { anyApi } from "convex/server";
import { v, ConvexError } from "convex/values";
import schema, { throttleProviderValidator } from "./schema";
import type { Doc } from "./_generated/dataModel";

function authorize(token: string) {
  if (
    process.env.COLLECTOR_MODE !== "outbound" ||
    !process.env.COLLECTOR_TOKEN ||
    token !== process.env.COLLECTOR_TOKEN
  )
    throw new ConvexError("Worker authentication failed.");
}
// How recently `lastSeen` must have moved for the worker to count as live.
// Mirrors src/integrationStatus.ts's WORKER_LIVE_WINDOW_MS exactly — keep
// the two in sync if this ever changes.
export const WORKER_LIVE_WINDOW_MS = 45_000;

// Presence is a caller-visible fact only through this helper, never through
// a bare `row.online` read: `online` alone cannot tell a worker that shut
// down cleanly from one that vanished mid-heartbeat and never got to say so.
// Combining it with freshness answers both — an explicit `online: false`
// (graceful shutdown, see `heartbeat` below) reads as offline immediately
// regardless of how recent `lastSeen` is, and a worker that stopped sending
// heartbeats without saying so decays to offline once `lastSeen` goes stale,
// with no scheduled write required to make that happen.
export function isWorkerLive(
  row: Pick<Doc<"collector">, "online" | "lastSeen"> | null | undefined,
  now: number,
): boolean {
  return !!row?.online && now - row.lastSeen < WORKER_LIVE_WINDOW_MS;
}

export const heartbeat = internalMutation({
  args: { online: v.boolean() },
  returns: v.null(),
  handler: async (ctx, { online }) => {
    const existing = await ctx.db
      .query("collector")
      .withIndex("by_name", (q) => q.eq("name", "desktop"))
      .unique();

    const lastSeen = Date.now();

    if (existing) await ctx.db.patch(existing._id, { online, lastSeen });
    else await ctx.db.insert("collector", { name: "desktop", online, lastSeen });

    // No scheduled `expire` here on purpose. It used to schedule a write
    // 45s out on every single heartbeat (every 5-8s in production), so
    // heartbeats and their own not-yet-fired expirations piled up against
    // the same single-row `collector` document and fought over it —
    // `npx convex insights --prod` showed 1000+ OCC retries on
    // `worker.js:expire` colliding with `worker.js:heartbeat`. Presence now
    // decays purely by `isWorkerLive` reading `lastSeen` against a caller's
    // own clock (see convex/integrations.ts), so nothing ever needs to run
    // just to flip a boolean once time has passed.
    return null;
  },
});

export const claimNext = internalMutation({
  args: {},
  returns: v.union(v.null(), schema.doc("jobs")),
  handler: async (ctx): Promise<Doc<"jobs"> | null> => {
    if (
      await ctx.db
        .query("jobs")
        .withIndex("by_status", (q) => q.eq("status", "running"))
        .first()
    )
      return null;

    const jobs = await ctx.db
      .query("jobs")
      .withIndex("by_status", (q) => q.eq("status", "queued"))
      .take(20);

    const job = jobs.find((j) => (j.readyAt ?? 0) <= Date.now());

    if (!job) return null;
    const attempt = job.attempt + 1;
    await ctx.db.patch(job._id, {
      status: "running",
      attempt,
      pageAttempt: (job.pageAttempt ?? 0) + 1,
      phase: "Starting download",
      updatedAt: Date.now(),
      error: undefined,
    });
    await ctx.scheduler.runAfter(600_000, internal.jobs.expire, {
      jobId: job._id,
      attempt,
    });

    return { ...job, status: "running", attempt };
  },
});

export const poll = action({
  args: {
    token: v.string(),
    heartbeatOnly: v.optional(v.boolean()),
    online: v.optional(v.boolean()),
    // What the worker just observed about the loopback capture receiver it
    // delivers to (scripts/production-worker.ts's `receiverHealth`). Purely
    // an observation, recorded into `serviceHealth` (convex/health.ts) so
    // the dashboard's receiver health stops being permanently unknown in
    // the deployment that actually runs.
    //
    // Optional on purpose, and omitted rather than guessed: the worker's
    // final shutdown poll reports `online: false` about *itself* without
    // having probed the receiver, and must not be allowed to claim the
    // receiver is down. No field means "this poll has nothing to say about
    // the receiver", never "the receiver is fine".
    receiver: v.optional(v.object({ healthy: v.boolean(), error: v.optional(v.string()) })),
  },
  returns: v.union(v.null(), schema.doc("jobs")),
  handler: async (ctx, args): Promise<Doc<"jobs"> | null> => {
    authorize(args.token);
    await ctx.runMutation(internal.worker.heartbeat, {
      online: args.online !== false,
    });

    if (args.receiver) {
      // Never allowed to break the worker's real work: a health row is a
      // side observation, so a failure to write one is logged and dropped
      // rather than turned into a failed poll (which would cost a job
      // claim). It also never touches any job's status.
      try {
        await ctx.runMutation(anyApi.health.record, {
          service: "receiver",
          healthy: args.receiver.healthy,
          error: args.receiver.error
            ? { message: args.receiver.error, observedAt: Date.now() }
            : undefined,
        });
      } catch (error) {
        console.error(
          `worker: could not record capture-receiver health: ${error instanceof Error ? error.message : String(error)}`,
        );
      }
    }

    if (args.heartbeatOnly || args.online === false) return null;

    return ctx.runMutation(internal.worker.claimNext, {});
  },
});

export const report = action({
  args: {
    token: v.string(),
    jobId: v.id("jobs"),
    attempt: v.number(),
    event: v.union(
      v.literal("phase"),
      v.literal("identity"),
      v.literal("receipt"),
      v.literal("finish"),
      // Production runs COLLECTOR_MODE=outbound, so the VM worker — not
      // convex/importer.ts — is what actually talks to x.md and therefore
      // the only thing that ever sees a provider asking us to slow down.
      // Without this event that observation dies on the worker and the
      // dashboard's provider-limits panel stays empty in the one deployment
      // that matters.
      v.literal("throttle"),
    ),
    phase: v.optional(v.string()),
    userId: v.optional(v.string()),
    captureId: v.optional(v.string()),
    receiptId: v.optional(v.string()),
    count: v.optional(v.number()),
    warnings: v.optional(v.array(v.string())),
    error: v.optional(v.string()),
    retryAfter: v.optional(v.number()),
    postsReceived: v.optional(v.number()),
    oldest: v.optional(v.string()),
    floorReached: v.optional(v.boolean()),
    nextUntil: v.optional(v.string()),
    nextCursor: v.optional(v.string()),
    expectedUserId: v.optional(v.string()),
    // The account this run turned out to be. Production runs
    // COLLECTOR_MODE=outbound, so this worker — not convex/importer.ts — is
    // what talks to x.md, and without this field the profile never reached
    // `jobs.finish`. That is the entire reason the production `accounts`
    // table was empty: identity was pinned on the job, but no account row
    // was ever created from it, so the account library had nothing to show
    // and every publication update was rejected as "no known account".
    profile: v.optional(
      v.object({
        handle: v.string(),
        userId: v.string(),
        name: v.string(),
        avatar: v.optional(v.string()),
      }),
    ),
    // Only read for the "throttle" event. Every field is the provider's own
    // report, forwarded verbatim; the worker never estimates one.
    throttle: v.optional(
      v.object({
        provider: throttleProviderValidator,
        operation: v.string(),
        reason: v.string(),
        remaining: v.optional(v.number()),
        resetAt: v.optional(v.number()),
        retryAfterMs: v.optional(v.number()),
        observedAt: v.optional(v.number()),
      }),
    ),
  },
  returns: v.null(),
  handler: async (ctx, args): Promise<null> => {
    authorize(args.token);
    const base = { jobId: args.jobId, attempt: args.attempt };

    if (args.event === "throttle") {
      // A throttle report is an observation, never a job state change: it
      // must not move the job's status, and a job that is no longer this
      // attempt should still have its observation recorded.
      //
      // A "throttle" event with no payload carries no observation at all.
      // Silently accepting it would report success for a call that recorded
      // nothing, which is worse than failing: the sender would never learn
      // its reports are being dropped.
      if (!args.throttle)
        throw new ConvexError("A throttle report must include the provider's own throttle facts.");
      await ctx.runMutation(internal.jobs.recordThrottle, { ...base, ...args.throttle });

      return null;
    }

    if (args.event === "phase")
      await ctx.runMutation(internal.jobs.progress, {
        ...base,
        phase: args.phase ?? "Downloading",
      });
    else if (args.event === "identity")
      await ctx.runMutation(internal.jobs.pinIdentity, {
        ...base,
        userId: args.userId!,
      });
    else if (args.event === "receipt")
      await ctx.runMutation(internal.jobs.ack, {
        ...base,
        captureId: args.captureId!,
        receiptId: args.receiptId!,
        count: args.count!,
      });
    else
      await ctx.runMutation(internal.jobs.finish, {
        ...base,
        warnings: args.warnings ?? [],
        error: args.error,
        retryAfter: args.retryAfter,
        postsReceived: args.postsReceived,
        oldest: args.oldest,
        floorReached: args.floorReached,
        nextUntil: args.nextUntil,
        nextCursor: args.nextCursor,
        expectedUserId: args.expectedUserId,
        profile: args.profile,
      });
    return null;
  },
});
