import { describe, expect, it } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import type { FunctionReference } from "convex/server";
import schema from "../convex/schema";
import type { Doc, Id } from "../convex/_generated/dataModel";
import type { AccountLibraryRow } from "../convex/lib/contracts";

const modules = import.meta.glob("../convex/**/*.ts");

// `anyApi` for the same reason the other suites use it: convex/_generated/
// api.d.ts is a build artifact regenerated by a command that talks to the
// deployment, so it is not regenerated here. These resolve to the same
// function references at runtime.
// SAFETY: `anyApi.jobs.finish` is typed as a generic `FunctionReference<any,
// any>` (convex/server's AnyApi), not `unknown` — this single narrowing to
// the reference's real, hand-checked args/return shape (matching
// convex/jobs.ts's `finish`) is what lets the calls below typecheck.
const finish = anyApi.jobs.finish as FunctionReference<
  "mutation",
  "internal",
  {
    jobId: Id<"jobs">;
    attempt: number;
    warnings: string[];
    profile?: { handle: string; userId: string; name: string; avatar?: string };
  },
  null
>;

// SAFETY: same narrowing as `finish` above, to convex/library.ts's real
// `rows` query shape.
const libraryRows = anyApi.library.rows as FunctionReference<
  "query",
  "public",
  Record<string, never>,
  { rows: AccountLibraryRow[]; truncated: boolean }
>;

async function setup() {
  const t = convexTest(schema, modules);
  const alice = await t.run((ctx) => ctx.db.insert("users", { isAnonymous: true }));

  return { t, alice, a: t.withIdentity({ subject: `${alice}|session` }) };
}

/** A job already in the state `finish` requires: running, on this attempt. */
async function runningJob(
  t: Awaited<ReturnType<typeof setup>>["t"],
  owner: Id<"users">,
  input: string,
  expectedUserId?: string,
) {
  return t.run((ctx) =>
    ctx.db.insert("jobs", {
      owner,
      kind: "bulk",
      input,
      expectedUserId,
      refresh: false,
      status: "running",
      count: 1,
      attempt: 1,
      warnings: [],
      updatedAt: Date.now(),
    }),
  );
}

const accounts = (t: Awaited<ReturnType<typeof setup>>["t"]) =>
  t.run((ctx) => ctx.db.query("accounts").collect());

describe("account identity on the write path", () => {
  it("gives a reassigned handle its own account row instead of overwriting the previous holder's identity", async () => {
    const { t, alice } = await setup();

    // The original holder of @moved.
    const first = await runningJob(t, alice, "moved");
    await t.mutation(finish, {
      jobId: first,
      attempt: 1,
      warnings: [],
      profile: { handle: "moved", userId: "111", name: "First Owner" },
    });

    // Later, a DIFFERENT provider account is found under the same handle.
    const second = await runningJob(t, alice, "moved");
    await t.mutation(finish, {
      jobId: second,
      attempt: 1,
      warnings: [],
      profile: { handle: "moved", userId: "222", name: "Second Owner" },
    });

    const rows = await accounts(t);
    expect(rows).toHaveLength(2);
    const byId = new Map(rows.map((row: Doc<"accounts">) => [row.userId, row]));
    // The whole point: the first account's identity and name are untouched.
    expect(byId.get("111")?.name).toBe("First Owner");
    expect(byId.get("222")?.name).toBe("Second Owner");
    // ...and neither row has had its userId rewritten to the other's.
    expect(byId.get("111")?._id).not.toEqual(byId.get("222")?._id);
  });

  it("treats the same provider id under a new handle as a rename, patching one row rather than adding another", async () => {
    const { t, alice } = await setup();
    const before = await runningJob(t, alice, "oldname");
    await t.mutation(finish, {
      jobId: before,
      attempt: 1,
      warnings: [],
      profile: { handle: "oldname", userId: "111", name: "Same Person" },
    });
    const after = await runningJob(t, alice, "newname");
    await t.mutation(finish, {
      jobId: after,
      attempt: 1,
      warnings: [],
      profile: { handle: "newname", userId: "111", name: "Same Person Renamed" },
    });

    const rows = await accounts(t);
    expect(rows).toHaveLength(1);
    expect(rows[0].userId).toBe("111");
    expect(rows[0].handle).toBe("newname");
    expect(rows[0].name).toBe("Same Person Renamed");

    // Both handles it has ever held are on record, which is what makes the
    // reassignment case answerable from data instead of guessed.
    const handles = await t.run((ctx) => ctx.db.query("accountHandles").collect());
    expect(handles.map((h) => h.handle).sort()).toEqual(["newname", "oldname"]);
    expect(new Set(handles.map((h) => String(h.accountId))).size).toBe(1);
  });

  it("keeps the two identities as separate library rows and never throws on the now-duplicated handle", async () => {
    const { t, alice, a } = await setup();

    for (const userId of ["111", "222"]) {
      const job = await runningJob(t, alice, "moved", userId);
      await t.mutation(finish, {
        jobId: job,
        attempt: 1,
        warnings: [],
        profile: { handle: "moved", userId, name: `Owner ${userId}` },
      });
    }

    // A by_handle read with two matching rows used to throw (`.unique()`).
    const rows = (await a.query(libraryRows, {})).rows;
    expect(rows).toHaveLength(2);
    expect(new Set(rows.map((row) => String(row.accountId))).size).toBe(2);
  });

  it("backfills the current handle into history the first time a pre-existing account (with no accountHandles rows yet) is renamed", async () => {
    const { t, alice } = await setup();
    // Simulates an account that predates accountHandles ever being written
    // for it (e.g. data from before this table/logic existed) — the account
    // row exists, but nothing has ever recorded its handle.
    const accountId = await t.run((ctx) =>
      ctx.db.insert("accounts", { handle: "legacy", userId: "777", name: "Legacy" }),
    );
    const handlesBefore = await t.run((ctx) =>
      ctx.db
        .query("accountHandles")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .collect(),
    );
    expect(handlesBefore).toHaveLength(0);

    const job = await runningJob(t, alice, "renamed", "777");
    await t.mutation(finish, {
      jobId: job,
      attempt: 1,
      warnings: [],
      profile: { handle: "renamed", userId: "777", name: "Legacy" },
    });

    // Without recording `existing.handle` before the patch, "legacy" would
    // never appear anywhere — the only recordHandle call left would be for
    // "renamed", and the account's very first handle would be gone the
    // moment its very first rename was detected.
    const handles = await t.run((ctx) =>
      ctx.db
        .query("accountHandles")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .collect(),
    );
    expect(handles.map((h) => h.handle).sort()).toEqual(["legacy", "renamed"]);
  });

  it("does not re-insert a handle the account has already seen more than 50 handles ago (recordHandle looks up the exact pair, not a capped scan)", async () => {
    const { t, alice } = await setup();
    const accountId = await t.run((ctx) =>
      ctx.db.insert("accounts", { handle: "current", userId: "999", name: "Many Handles" }),
    );
    // More than the old take(50) cap's worth of handle history, seeded
    // directly. `.take(50)` with no explicit order reads ascending
    // `_creationTime` — the OLDEST 50 — so a handle recorded after that
    // window (like the 60th one below) could never be found by that scan,
    // and would have been re-inserted as a "new" handle it had already seen.
    const seededHandles = Array.from({ length: 60 }, (_, i) => `h${i}`);
    await t.run(async (ctx) => {
      for (const handle of seededHandles)
        await ctx.db.insert("accountHandles", {
          accountId,
          handle,
          firstSeenAt: Date.now(),
          lastSeenAt: Date.now(),
        });
    });
    const target = seededHandles[59];
    const job = await runningJob(t, alice, target, "999");
    await t.mutation(finish, {
      jobId: job,
      attempt: 1,
      warnings: [],
      profile: { handle: target, userId: "999", name: "Many Handles" },
    });

    const matching = await t.run((ctx) =>
      ctx.db
        .query("accountHandles")
        .withIndex("by_account_and_handle", (q) =>
          q.eq("accountId", accountId).eq("handle", target),
        )
        .collect(),
    );
    expect(matching).toHaveLength(1);
  });
});
