import { describe, expect, it } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import schema from "../convex/schema";
import type { Id } from "../convex/_generated/dataModel";

const modules = import.meta.glob("../convex/**/*.ts");

// convex/_generated/api.d.ts is a build artifact regenerated by
// `npx convex dev`/`convex codegen` (both of which talk to the deployment)
// and does not yet declare the `limits` module — see convex/publication.ts's
// header comment for the same situation. `anyApi` resolves to the exact same
// function references at runtime as the generated `internal`/`api` objects
// would once codegen has run.
const current = anyApi.limits.current;
const all = anyApi.limits.all;

function setup() {
  const t = convexTest(schema, modules);
  return t;
}

async function withUser(t: ReturnType<typeof setup>) {
  const userId: Id<"users"> = await t.run((ctx) => ctx.db.insert("users", { isAnonymous: true }));
  return { a: t.withIdentity({ subject: `${userId}|session` }), userId };
}

async function seedThrottleEvent(
  t: ReturnType<typeof setup>,
  overrides: {
    provider?: "xmd" | "receiver" | "search";
    operation?: string;
    reason?: string;
    remaining?: number;
    resetAt?: number;
    retryAfterMs?: number;
    observedAt?: number;
  } = {},
) {
  return t.run((ctx) =>
    ctx.db.insert("providerThrottleEvents", {
      provider: overrides.provider ?? "xmd",
      operation: overrides.operation ?? "history",
      reason: overrides.reason ?? "x.md rate limit reached.",
      remaining: overrides.remaining,
      resetAt: overrides.resetAt,
      retryAfterMs: overrides.retryAfterMs,
      observedAt: overrides.observedAt ?? Date.now(),
    }),
  );
}

describe("provider limits (docs/publication-contract.md 'Provider throttle facts')", () => {
  it("requires a signed-in caller", async () => {
    const t = setup();
    await expect(t.query(current, { provider: "xmd" })).rejects.toThrow(
      "Start a session to use your workspace.",
    );
  });

  it("reports a live throttle WITH a provider-supplied remaining allowance", async () => {
    const t = setup();
    const observedAt = Date.now();
    await seedThrottleEvent(t, {
      provider: "xmd",
      operation: "history",
      reason: "x.md rate limit reached. The job will retry after the provider's delay.",
      remaining: 3,
      resetAt: observedAt + 3_600_000,
      retryAfterMs: 30_000,
      observedAt,
    });
    const { a } = await withUser(t);
    expect(await a.query(current, { provider: "xmd" })).toEqual({
      kind: "throttled",
      provider: "xmd",
      operation: "history",
      reason: "x.md rate limit reached. The job will retry after the provider's delay.",
      remaining: { kind: "known", value: 3 },
      resetAt: observedAt + 3_600_000,
      nextRetryAt: observedAt + 30_000,
      observedAt,
    });
  });

  it("reports a live throttle with NO remaining-allowance figure as honestly unknown, never 0 or a guess", async () => {
    const t = setup();
    const observedAt = Date.now();
    await seedThrottleEvent(t, {
      provider: "search",
      operation: "query",
      reason: "search service returned 429 with no allowance header.",
      remaining: undefined,
      resetAt: undefined,
      retryAfterMs: 5_000,
      observedAt,
    });
    const { a } = await withUser(t);
    const result = await a.query(current, { provider: "search" });
    expect(result).toMatchObject({
      kind: "throttled",
      provider: "search",
      remaining: { kind: "unknown" },
    });
    // "unknown" must never carry a numeric value field at all.
    expect(result).not.toHaveProperty("remaining.value");
    expect((result as { resetAt?: number }).resetAt).toBeUndefined();
    expect(result).toMatchObject({ nextRetryAt: observedAt + 5_000 });
  });

  it("never presents a stale historical jobs.error string as the current limit", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);
    // An old job carrying the exact pre-PR#12 daily-limit message, with no
    // providerThrottleEvents row at all for any provider.
    await t.run((ctx) =>
      ctx.db.insert("jobs", {
        owner: userId,
        kind: "bulk",
        input: "someone",
        refresh: false,
        status: "failed",
        count: 12,
        attempt: 3,
        warnings: [],
        error: "Paused at today's import limit. Your downloaded posts are safe. Try again tomorrow.",
        updatedAt: Date.now(),
      }),
    );
    expect(await a.query(current, { provider: "xmd" })).toEqual({ kind: "none", provider: "xmd" });
    expect(await a.query(all, {})).toEqual([
      { kind: "none", provider: "xmd" },
      { kind: "none", provider: "receiver" },
      { kind: "none", provider: "search" },
    ]);
  });

  it("picks the most recent observation by observedAt, not by insertion order", async () => {
    const t = setup();
    const older = Date.now() - 60_000;
    const newer = Date.now();
    // Inserted out of order: the newer-by-observedAt row is written first.
    await seedThrottleEvent(t, {
      provider: "receiver",
      operation: "handoff",
      reason: "receiver still recovering from the earlier spike.",
      remaining: 0,
      observedAt: newer,
    });
    await seedThrottleEvent(t, {
      provider: "receiver",
      operation: "handoff",
      reason: "an older, since-superseded observation.",
      remaining: 9,
      observedAt: older,
    });
    const { a } = await withUser(t);
    const result = await a.query(current, { provider: "receiver" });
    expect(result).toMatchObject({
      reason: "receiver still recovering from the earlier spike.",
      observedAt: newer,
      remaining: { kind: "known", value: 0 },
    });
  });

  it("all() covers every provider in one call, mixing throttled and none", async () => {
    const t = setup();
    await seedThrottleEvent(t, { provider: "xmd", remaining: 1, observedAt: Date.now() });
    const { a } = await withUser(t);
    const result = await a.query(all, {});
    expect(result).toHaveLength(3);
    expect(result.find((r: { provider: string }) => r.provider === "xmd")).toMatchObject({
      kind: "throttled",
      remaining: { kind: "known", value: 1 },
    });
    expect(result.find((r: { provider: string }) => r.provider === "receiver")).toEqual({
      kind: "none",
      provider: "receiver",
    });
    expect(result.find((r: { provider: string }) => r.provider === "search")).toEqual({
      kind: "none",
      provider: "search",
    });
  });
});
