import { afterEach, describe, expect, it, vi } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import schema from "../convex/schema";
import type { PublicationUpdateEnvelope } from "../convex/lib/contracts";

const modules = import.meta.glob("../convex/**/*.ts");

// convex/_generated/api.d.ts is a build artifact regenerated by
// `npx convex dev`/`convex codegen` (both of which talk to the deployment)
// and is out of scope for this unit — see convex/publication.ts's header
// comment. `anyApi` resolves to the exact same function references at
// runtime as the generated `internal`/`api` objects would.
const applyUpdate = anyApi.publication.applyUpdate;

afterEach(() => {
  vi.unstubAllEnvs();
});

function setup() {
  return convexTest(schema, modules);
}

async function seedAccount(
  t: ReturnType<typeof setup>,
  overrides: { handle?: string; userId?: string; name?: string } = {},
) {
  return t.run((ctx) =>
    ctx.db.insert("accounts", {
      handle: overrides.handle ?? "alice",
      userId: overrides.userId ?? "111",
      name: overrides.name ?? "Alice",
    }),
  );
}

function envelope(overrides: Partial<PublicationUpdateEnvelope> = {}): PublicationUpdateEnvelope {
  return {
    version: 1 as const,
    handle: "alice",
    captureIds: [],
    generation: 1,
    reportedState: "indexing" as const,
    observedAt: Date.now(),
    ...overrides,
  };
}

describe("publication update receiver (docs/publication-contract.md)", () => {
  it("applies the first update for an account and creates its publication row", async () => {
    const t = setup();
    const accountId = await seedAccount(t);

    const result = await t.mutation(
      applyUpdate,
      envelope({ providerAccountId: "111", generation: 1, reportedState: "indexing" }),
    );

    expect(result).toEqual({ outcome: "applied", committedGeneration: 1 });

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row).toMatchObject({ accountId, state: "indexing", committedGeneration: 1 });
    const logs = await t.run((ctx) => ctx.db.query("publicationUpdates").collect());
    expect(logs).toHaveLength(1);
    expect(logs[0]).toMatchObject({ outcome: "applied", accountId, generation: 1 });
  });

  it("is idempotent: a duplicate generation never double-applies and returns the same acceptance", async () => {
    const t = setup();
    const accountId = await seedAccount(t);
    await t.mutation(
      applyUpdate,
      envelope({ providerAccountId: "111", generation: 1, reportedState: "indexing" }),
    );

    // Resend the same generation with different content on purpose: a
    // duplicate must be a true no-op, not a reinterpretation of the stored
    // state, even when the resent payload disagrees with what's on record.
    const result = await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 1,
        reportedState: "failed",
        error: { message: "boom" },
      }),
    );

    expect(result).toEqual({ outcome: "duplicate_ignored", committedGeneration: 1 });

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row?.state).toBe("indexing");
    const logs = await t.run((ctx) => ctx.db.query("publicationUpdates").collect());
    expect(logs).toHaveLength(2);
    expect(logs[1]).toMatchObject({ outcome: "duplicate_ignored", generation: 1 });
  });

  it("rejects a stale, out-of-order update without regressing the displayed state", async () => {
    const t = setup();
    const accountId = await seedAccount(t);
    await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 5,
        reportedState: "searchable",
        uniquePostCount: 4000,
        uniquePostCountAsOf: 1000,
      }),
    );

    const stale = await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 3,
        reportedState: "failed",
        error: { message: "a slow, out-of-order retry" },
      }),
    );

    expect(stale).toEqual({ outcome: "stale_ignored", committedGeneration: 5 });

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row).toMatchObject({
      state: "searchable",
      committedGeneration: 5,
      searchablePostCount: 4000,
      searchablePostCountAsOf: 1000,
    });
    const logs = await t.run((ctx) => ctx.db.query("publicationUpdates").collect());
    expect(logs[1]).toMatchObject({ outcome: "stale_ignored", generation: 3 });
  });

  it("moves state to failed on a newer generation without erasing the last searchable snapshot", async () => {
    const t = setup();
    const accountId = await seedAccount(t);

    const applied = await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 5,
        reportedState: "searchable",
        uniquePostCount: 4000,
        uniquePostCountAsOf: 1000,
      }),
    );

    expect(applied.outcome).toBe("applied");

    const failed = await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 6,
        reportedState: "failed",
        error: { message: "indexer crashed" },
      }),
    );

    expect(failed).toEqual({ outcome: "applied", committedGeneration: 6 });

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row).toMatchObject({
      state: "failed",
      committedGeneration: 6,
      // Non-regression: the earlier confirmed-good snapshot survives a
      // later failure exactly as docs/publication-contract.md requires.
      searchablePostCount: 4000,
      searchablePostCountAsOf: 1000,
      lastError: { message: "indexer crashed", generation: 6 },
    });
  });

  it("round-trips an accepted update's pendingWork onto the accountPublications row", async () => {
    const t = setup();
    const accountId = await seedAccount(t);

    const result = await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 1,
        reportedState: "indexing",
        pendingWork: { unit: "jobs", count: 3 },
      }),
    );

    expect(result.outcome).toBe("applied");

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row?.pendingWork).toEqual({ unit: "jobs", count: 3 });
  });

  it("keeps the last known pendingWork when a later applied update omits it (sticky, matching lastError)", async () => {
    const t = setup();
    const accountId = await seedAccount(t);
    await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 1,
        reportedState: "indexing",
        pendingWork: { unit: "jobs", count: 3 },
      }),
    );

    // This update reports "searchable" and says nothing about pendingWork —
    // per docs/publication-contract.md ("omit when unknown"), that means
    // "unknown", not "none left", so the earlier value must survive.
    const result = await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 2,
        reportedState: "searchable",
        uniquePostCount: 10,
        uniquePostCountAsOf: 1000,
      }),
    );

    expect(result.outcome).toBe("applied");

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row?.pendingWork).toEqual({ unit: "jobs", count: 3 });
  });

  it("overwrites pendingWork when a later applied update reports a new value, including zero", async () => {
    const t = setup();
    const accountId = await seedAccount(t);
    await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 1,
        reportedState: "indexing",
        pendingWork: { unit: "jobs", count: 3 },
      }),
    );
    await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        generation: 2,
        reportedState: "indexing",
        pendingWork: { unit: "jobs", count: 0 },
      }),
    );

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row?.pendingWork).toEqual({ unit: "jobs", count: 0 });
  });

  it("rejects a failed report with no error and does not create a publication row", async () => {
    const t = setup();
    await seedAccount(t);

    const result = await t.mutation(
      applyUpdate,
      envelope({ providerAccountId: "111", reportedState: "failed" }),
    );

    expect(result.outcome).toBe("rejected_invalid");
    expect(await t.run((ctx) => ctx.db.query("accountPublications").collect())).toEqual([]);
    const logs = await t.run((ctx) => ctx.db.query("publicationUpdates").collect());
    expect(logs[0]).toMatchObject({ outcome: "rejected_invalid" });
  });

  it("rejects a searchable count with no observation time rather than guess one", async () => {
    const t = setup();
    await seedAccount(t);

    const result = await t.mutation(
      applyUpdate,
      envelope({ providerAccountId: "111", reportedState: "searchable", uniquePostCount: 10 }),
    );

    expect(result.outcome).toBe("rejected_invalid");
    expect(await t.run((ctx) => ctx.db.query("accountPublications").collect())).toEqual([]);
  });

  it("rejects an update that cannot resolve to a known account, and never invents one", async () => {
    const t = setup();

    const result = await t.mutation(
      applyUpdate,
      envelope({ providerAccountId: "does-not-exist", handle: "ghost" }),
    );

    expect(result.outcome).toBe("rejected_invalid");
    expect(await t.run((ctx) => ctx.db.query("accounts").collect())).toEqual([]);
    const logs = await t.run((ctx) => ctx.db.query("publicationUpdates").collect());
    expect(logs[0]).toMatchObject({ outcome: "rejected_invalid" });
    expect(logs[0].accountId).toBeUndefined();
  });

  it("never falls back to a handle match once a provider id is asserted and unmatched (anti-merge)", async () => {
    const t = setup();
    const aliceId = await seedAccount(t, { handle: "alice", userId: "111" });
    await seedAccount(t, { handle: "bob", userId: "222" });

    // Reassignment-shaped update: an unknown provider id whose handle
    // happens to match a different, real account. Must not merge into it.
    const result = await t.mutation(
      applyUpdate,
      envelope({ providerAccountId: "999-unknown", handle: "alice" }),
    );

    expect(result.outcome).toBe("rejected_invalid");

    const aliceRow = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", aliceId))
        .unique(),
    );

    expect(aliceRow).toBeNull();
  });

  it("rejects an ambiguous handle match instead of throwing (two accounts, one handle)", async () => {
    // accounts.by_handle is not uniqueness-enforced, so `.unique()` here would
    // throw and surface as a 500 rather than the contract's rejected_invalid.
    const t = setup();
    await seedAccount(t, { handle: "twin", userId: "1" });
    await seedAccount(t, { handle: "twin", userId: "2" });
    const result = await t.mutation(applyUpdate, envelope({ handle: "twin", generation: 1 }));
    expect(result.outcome).toBe("rejected_invalid");
    const rows = await t.run((ctx) => ctx.db.query("accountPublications").collect());
    expect(rows).toHaveLength(0);
  });

  it("falls back to handle only when the update asserts no provider id at all", async () => {
    const t = setup();
    const accountId = await seedAccount(t, { handle: "alice", userId: "111" });
    const result = await t.mutation(applyUpdate, envelope({ handle: "alice" }));
    expect(result.outcome).toBe("applied");

    const row = await t.run((ctx) =>
      ctx.db
        .query("accountPublications")
        .withIndex("by_account", (q) => q.eq("accountId", accountId))
        .unique(),
    );

    expect(row?.accountId).toBe(accountId);
  });

  it("never restarts or triggers acquisition: jobs are untouched by a publication update", async () => {
    const t = setup();
    await seedAccount(t);
    const owner = await t.run((ctx) => ctx.db.insert("users", { isAnonymous: true }));

    const jobId = await t.run((ctx) =>
      ctx.db.insert("jobs", {
        owner,
        kind: "bulk",
        input: "alice",
        status: "complete",
        count: 5,
        attempt: 1,
        refresh: false,
        warnings: [],
        updatedAt: 0,
      }),
    );

    await t.mutation(
      applyUpdate,
      envelope({
        providerAccountId: "111",
        reportedState: "searchable",
        uniquePostCount: 5,
        uniquePostCountAsOf: 1,
      }),
    );
    const jobs = await t.run((ctx) => ctx.db.query("jobs").collect());
    expect(jobs).toHaveLength(1);
    expect(jobs[0]).toMatchObject({ _id: jobId, status: "complete", updatedAt: 0 });
  });

  it("treats a raw capture receipt as downloaded only — it never creates or advances publication state", async () => {
    const t = setup();
    await seedAccount(t);
    const owner = await t.run((ctx) => ctx.db.insert("users", { isAnonymous: true }));

    const jobId = await t.run((ctx) =>
      ctx.db.insert("jobs", {
        owner,
        kind: "bulk",
        input: "alice",
        status: "complete",
        count: 5,
        attempt: 1,
        refresh: false,
        warnings: [],
        updatedAt: 0,
      }),
    );

    await t.run((ctx) =>
      ctx.db.insert("receipts", { jobId, captureId: "cap1", receiptId: "r1", records: 5 }),
    );
    // A durable raw-capture receipt exists, but no publication update has
    // arrived: accountPublications must stay untouched (no "searchable",
    // no row at all) until a confirmed update says otherwise.
    expect(await t.run((ctx) => ctx.db.query("accountPublications").collect())).toEqual([]);
  });

  describe("HTTP transport (convex/http.ts POST /publication/update)", () => {
    it("fails closed with 401 when the bearer token is missing or wrong", async () => {
      const t = setup();
      await seedAccount(t);
      vi.stubEnv("PUBLICATION_SERVICE_TOKEN", "secret");

      const res = await t.fetch("/publication/update", {
        method: "POST",
        headers: { Authorization: "Bearer wrong", "Content-Type": "application/json" },
        body: JSON.stringify(envelope({ providerAccountId: "111" })),
      });

      expect(res.status).toBe(401);
      expect(await t.run((ctx) => ctx.db.query("publicationUpdates").collect())).toEqual([]);
    });

    it("fails closed with 401 when no service token is configured at all", async () => {
      const t = setup();
      await seedAccount(t);

      const res = await t.fetch("/publication/update", {
        method: "POST",
        headers: { Authorization: "Bearer anything", "Content-Type": "application/json" },
        body: JSON.stringify(envelope({ providerAccountId: "111" })),
      });

      expect(res.status).toBe(401);
    });

    it("rejects a body that does not match the publication envelope with 400", async () => {
      const t = setup();
      vi.stubEnv("PUBLICATION_SERVICE_TOKEN", "secret");

      const res = await t.fetch("/publication/update", {
        method: "POST",
        headers: { Authorization: "Bearer secret", "Content-Type": "application/json" },
        body: JSON.stringify({ foo: "bar" }),
      });

      expect(res.status).toBe(400);
    });

    it("fails closed with 400 on an otherwise well-formed body carrying an unknown extra field, instead of crashing the mutation's strict validator", async () => {
      const t = setup();
      await seedAccount(t);
      vi.stubEnv("PUBLICATION_SERVICE_TOKEN", "secret");

      const res = await t.fetch("/publication/update", {
        method: "POST",
        headers: { Authorization: "Bearer secret", "Content-Type": "application/json" },
        body: JSON.stringify({
          ...envelope({ providerAccountId: "111" }),
          debugExtra: "should never reach applyUpdate",
        }),
      });

      expect(res.status).toBe(400);
      expect(await t.run((ctx) => ctx.db.query("accountPublications").collect())).toEqual([]);
      expect(await t.run((ctx) => ctx.db.query("publicationUpdates").collect())).toEqual([]);
    });

    it("fails closed with 400 when a nested pendingWork/error object carries an unknown extra field", async () => {
      const t = setup();
      await seedAccount(t);
      vi.stubEnv("PUBLICATION_SERVICE_TOKEN", "secret");

      const res = await t.fetch("/publication/update", {
        method: "POST",
        headers: { Authorization: "Bearer secret", "Content-Type": "application/json" },
        // The extra field is added outside `envelope()`'s own (contract-
        // shaped) return type on purpose: it is exactly the malformed input
        // this test proves gets rejected, not a shape `envelope()` itself
        // should ever be able to produce.
        body: JSON.stringify({
          ...envelope({ providerAccountId: "111" }),
          pendingWork: { unit: "posts", count: 1, extra: "nope" },
        }),
      });

      expect(res.status).toBe(400);
    });

    it("accepts an authenticated, well-formed update end-to-end over HTTP", async () => {
      const t = setup();
      const accountId = await seedAccount(t);
      vi.stubEnv("PUBLICATION_SERVICE_TOKEN", "secret");

      const res = await t.fetch("/publication/update", {
        method: "POST",
        headers: { Authorization: "Bearer secret", "Content-Type": "application/json" },
        body: JSON.stringify(envelope({ providerAccountId: "111", generation: 1 })),
      });

      expect(res.status).toBe(200);
      expect(await res.json()).toEqual({ outcome: "applied", committedGeneration: 1 });

      const row = await t.run((ctx) =>
        ctx.db
          .query("accountPublications")
          .withIndex("by_account", (q) => q.eq("accountId", accountId))
          .unique(),
      );

      expect(row?.state).toBe("indexing");
    });

    it("supports the legacy DATA_SERVICE_TOKEN fallback like the other service capabilities", async () => {
      const t = setup();
      await seedAccount(t);
      vi.stubEnv("DATA_SERVICE_TOKEN", "legacy");

      const res = await t.fetch("/publication/update", {
        method: "POST",
        headers: { Authorization: "Bearer legacy", "Content-Type": "application/json" },
        body: JSON.stringify(envelope({ providerAccountId: "111" })),
      });

      expect(res.status).toBe(200);
    });
  });
});
