import { describe, expect, it } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import schema from "../convex/schema";
import type { Id } from "../convex/_generated/dataModel";
import type { DashboardSummary } from "../convex/lib/contracts";

/**
 * to-do.md: "Show queued-post counts only when known. Unknown provider
 * history size is 'unknown,' not zero or an invented estimate. Do not label
 * a count of files as a count of posts."
 *
 * The thing under test is `summary.summary`'s `providerQueuedWork`
 * (convex/lib/contracts.ts): the indexer's own `pendingWork` report, carried
 * out to the dashboard as one `Count` per unit it may report in. Four
 * properties matter here and each has a test below:
 *   - a reported posts count is surfaced, in posts;
 *   - an account that never reported contributes nothing — not a zero;
 *   - two accounts reporting different units are never summed together;
 *   - another owner's account is never folded into this caller's figure.
 */

const modules = import.meta.glob("../convex/**/*.ts");
// `anyApi`, not the generated `api`: convex/_generated/api.d.ts is a build
// artifact regenerated by `convex dev`/`convex codegen` against a live
// deployment and is not regenerated here. Same pattern as
// tests/summary.test.ts; it resolves to the same function reference at
// runtime. `now` is a required arg (convex/summary.ts never reads the wall
// clock inside the handler), so every call passes it.
const summaryQuery = anyApi.summary.summary as unknown as import("convex/server").FunctionReference<
  "query",
  "public",
  { now: number },
  DashboardSummary
>;

type PendingWork = { unit: "jobs" | "captures" | "posts"; count: number };

async function setup() {
  const t = convexTest(schema, modules);
  const [alice, bob] = await t.run(async (ctx) => [
    await ctx.db.insert("users", { isAnonymous: true }),
    await ctx.db.insert("users", { isAnonymous: true }),
  ]);
  return {
    t,
    alice,
    bob,
    a: t.withIdentity({ subject: `${alice}|session` }),
    b: t.withIdentity({ subject: `${bob}|session` }),
  };
}

/**
 * One imported account belonging to `owner`, with a publication row that
 * reports `pendingWork` (or deliberately does not). Mirrors what a real
 * bulk import plus an accepted publication update leaves behind: a `bulk`
 * job owned by the caller, an `accounts` row it resolves to by provider id,
 * and an `accountPublications` row — see convex/publication.ts applyUpdate.
 */
async function seedImportedAccount(
  t: Awaited<ReturnType<typeof setup>>["t"],
  owner: Id<"users">,
  args: {
    handle: string;
    userId: string;
    state?: "downloaded" | "waiting_for_indexing" | "indexing" | "searchable" | "failed";
    searchablePostCount?: number;
    pendingWork?: PendingWork;
    publication?: boolean;
  },
) {
  return t.run(async (ctx) => {
    const accountId = await ctx.db.insert("accounts", {
      handle: args.handle,
      userId: args.userId,
      name: args.handle,
    });
    await ctx.db.insert("jobs", {
      owner,
      kind: "bulk",
      input: args.handle,
      expectedUserId: args.userId,
      refresh: false,
      status: "complete",
      count: 0,
      attempt: 1,
      warnings: [],
      updatedAt: Date.now(),
    });
    if (args.publication !== false) {
      await ctx.db.insert("accountPublications", {
        accountId,
        state: args.state ?? "indexing",
        committedGeneration: 1,
        searchablePostCount: args.searchablePostCount,
        pendingWork: args.pendingWork,
        updatedAt: Date.now(),
      });
    }
    return accountId;
  });
}

describe("summary.summary providerQueuedWork", () => {
  it("surfaces an account's indexer-reported queued posts, labelled in posts", async () => {
    const { t, alice, a } = await setup();
    await seedImportedAccount(t, alice, {
      handle: "adam",
      userId: "1",
      pendingWork: { unit: "posts", count: 250 },
    });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.providerQueuedWork.posts).toEqual({ kind: "known", unit: "posts", value: 250 });
    // Nothing was reported in the other two units, so they stay unknown
    // rather than borrowing the posts figure or reading as a zero.
    expect(result.providerQueuedWork.captures).toEqual({ kind: "unknown", unit: "captures" });
    expect(result.providerQueuedWork.jobs).toEqual({ kind: "unknown", unit: "jobs" });
  });

  it("adds up several accounts reporting the SAME unit, and only that unit", async () => {
    const { t, alice, a } = await setup();
    await seedImportedAccount(t, alice, {
      handle: "one",
      userId: "1",
      pendingWork: { unit: "posts", count: 40 },
    });
    await seedImportedAccount(t, alice, {
      handle: "two",
      userId: "2",
      pendingWork: { unit: "posts", count: 2 },
    });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.providerQueuedWork.posts).toEqual({ kind: "known", unit: "posts", value: 42 });
  });

  it("an account that never reported pendingWork contributes nothing — the figure is unknown, not zero", async () => {
    const { t, alice, a } = await setup();
    // A real, fully imported and currently indexing account. The indexer has
    // simply never said anything about outstanding work for it, which is not
    // the same as saying there is none (convex/publication.ts: an update
    // omitting pendingWork has "nothing to say about outstanding work").
    await seedImportedAccount(t, alice, { handle: "silent", userId: "1", state: "indexing" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.providerQueuedWork.posts).toEqual({ kind: "unknown", unit: "posts" });
    expect(result.providerQueuedWork.captures).toEqual({ kind: "unknown", unit: "captures" });
    expect(result.providerQueuedWork.jobs).toEqual({ kind: "unknown", unit: "jobs" });
    // And the rest of the summary is unaffected: this account is genuinely
    // known to have no searchable posts yet.
    expect(result.indexedPosts).toEqual({ kind: "known", unit: "posts", value: 0 });
  });

  it("a silent account does not drag a reporting account's count down to zero, and does not turn it unknown", async () => {
    const { t, alice, a } = await setup();
    await seedImportedAccount(t, alice, {
      handle: "reports",
      userId: "1",
      pendingWork: { unit: "posts", count: 7 },
    });
    await seedImportedAccount(t, alice, { handle: "silent", userId: "2" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.providerQueuedWork.posts).toEqual({ kind: "known", unit: "posts", value: 7 });
  });

  it("a reported zero is a known zero — distinct from never having been told", async () => {
    const { t, alice, a } = await setup();
    await seedImportedAccount(t, alice, {
      handle: "finished",
      userId: "1",
      state: "searchable",
      searchablePostCount: 500,
      pendingWork: { unit: "posts", count: 0 },
    });
    const result = await a.query(summaryQuery, { now: Date.now() });
    // "The indexer looked and nothing is left" is a claim we may make,
    // because someone actually made it to us.
    expect(result.providerQueuedWork.posts).toEqual({ kind: "known", unit: "posts", value: 0 });
    expect(result.providerQueuedWork.captures).toEqual({ kind: "unknown", unit: "captures" });
  });

  it("never sums incompatible units: captures, jobs and posts each keep their own count", async () => {
    const { t, alice, a } = await setup();
    await seedImportedAccount(t, alice, {
      handle: "in-posts",
      userId: "1",
      pendingWork: { unit: "posts", count: 5 },
    });
    await seedImportedAccount(t, alice, {
      handle: "in-captures",
      userId: "2",
      pendingWork: { unit: "captures", count: 3 },
    });
    await seedImportedAccount(t, alice, {
      handle: "in-jobs",
      userId: "3",
      pendingWork: { unit: "jobs", count: 2 },
    });
    const result = await a.query(summaryQuery, { now: Date.now() });
    // The forbidden outcome is 10 of anything, and especially "10 posts":
    // a capture is a file and a job is a run, and neither is a post.
    expect(result.providerQueuedWork).toEqual({
      posts: { kind: "known", unit: "posts", value: 5 },
      captures: { kind: "known", unit: "captures", value: 3 },
      jobs: { kind: "known", unit: "jobs", value: 2 },
    });
    const values = Object.values(result.providerQueuedWork).map((count) =>
      count.kind === "known" ? count.value : null,
    );
    expect(values).not.toContain(10);
  });

  it("scopes the figure to the caller's own imports: another owner's reported work is never counted as yours", async () => {
    const { t, alice, bob, a, b } = await setup();
    await seedImportedAccount(t, alice, {
      handle: "alice-account",
      userId: "1",
      pendingWork: { unit: "posts", count: 99 },
    });
    // Bob imported nothing; alice's backlog is not his to see, and the
    // honest answer for him is "unknown", not 0 and certainly not 99.
    const bobs = await b.query(summaryQuery, { now: Date.now() });
    expect(bobs.providerQueuedWork.posts).toEqual({ kind: "unknown", unit: "posts" });

    // Bob's own import, reporting its own number, is all he ever sees.
    await seedImportedAccount(t, bob, {
      handle: "bob-account",
      userId: "2",
      pendingWork: { unit: "posts", count: 4 },
    });
    const bobsOwn = await b.query(summaryQuery, { now: Date.now() });
    expect(bobsOwn.providerQueuedWork.posts).toEqual({ kind: "known", unit: "posts", value: 4 });

    // Alice's figure never picked up bob's 4 either.
    const alices = await a.query(summaryQuery, { now: Date.now() });
    expect(alices.providerQueuedWork.posts).toEqual({ kind: "known", unit: "posts", value: 99 });
  });

  it("ignores pendingWork on an account this caller never imported, even though the row exists", async () => {
    const { t, alice, bob, a } = await setup();
    // Bob's import; alice has one of her own that says nothing about
    // outstanding work. Alice must still read "unknown" — the existence of
    // somebody else's number is not information about her corpus.
    await seedImportedAccount(t, bob, {
      handle: "bob-account",
      userId: "2",
      pendingWork: { unit: "captures", count: 12 },
    });
    await seedImportedAccount(t, alice, { handle: "alice-account", userId: "1" });
    const alices = await a.query(summaryQuery, { now: Date.now() });
    expect(alices.providerQueuedWork.captures).toEqual({ kind: "unknown", unit: "captures" });
  });

  it("requires authentication", async () => {
    const { t } = await setup();
    await expect(t.query(summaryQuery, { now: Date.now() })).rejects.toThrow();
  });
});
