import { describe, expect, it, vi } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import type { FunctionReference } from "convex/server";
import schema from "../convex/schema";
import type { Id } from "../convex/_generated/dataModel";
import type { Timeline } from "../convex/queue";

const modules = import.meta.glob("../convex/**/*.ts");

// convex/_generated/api.d.ts is a build artifact regenerated by
// `npx convex dev`/`convex codegen` and does not yet know about
// convex/queue.ts — same situation as convex/summary.ts and convex/limits.ts
// (see their own test files' header comments); `anyApi` resolves to the
// exact same function reference at runtime as the generated `api` object
// would once codegen has run.
// SAFETY: `anyApi.queue.timelineSnapshot` is `FunctionReference<any, any>` only
// because codegen hasn't caught up (see above); convex-test rejects the
// reference outright if `convex/queue.ts` did not actually register a
// `timeline` query, so this narrowing to its real, frozen signature is
// checked at every test run, not merely asserted away.
const timeline = anyApi.queue.timelineSnapshot as FunctionReference<
  "query",
  "public",
  { now: number; operatorToken?: string },
  Timeline
>;

function setup() {
  return convexTest(schema, modules);
}

// `timeline` is operator-gated (convex/access.ts `requireOperator`), same as
// `jobs.start`/`cancel`/`retry` — a verified email on the test-only
// OPERATOR_EMAILS allowlist (tests/setupEnv.ts) is what makes this caller an
// operator, mirroring tests/repeat-start.test.ts's own fixture.
async function withOperator(t: ReturnType<typeof setup>) {
  const userId: Id<"users"> = await t.run((ctx) =>
    ctx.db.insert("users", {
      isAnonymous: false,
      email: "operator@test.xearch",
      emailVerificationTime: Date.now(),
    }),
  );

  return { a: t.withIdentity({ subject: `${userId}|session` }), userId };
}

// A real, signed-in session with no verified operator email at all — the
// exact caller CodeRabbit's security finding says `user(ctx)` used to admit.
async function withNonOperator(t: ReturnType<typeof setup>) {
  const userId: Id<"users"> = await t.run((ctx) => ctx.db.insert("users", { isAnonymous: true }));

  return { a: t.withIdentity({ subject: `${userId}|session` }), userId };
}

type JobOverrides = Partial<{
  kind: "bulk" | "live" | "post" | "profile" | "following" | "followers" | "archive";
  input: string;
  status: "queued" | "running" | "complete" | "partial" | "failed" | "cancelled";
  count: number;
  attempt: number;
  pages: number;
  pageAttempt: number;
  postsReceived: number;
  readyAt: number;
  retryable: boolean;
  floorReached: boolean;
  updatedAt: number;
  attemptStartedAt: number;
  error: string;
  dismissedAt: number;
  expectedUserId: string;
}>;

async function seedJob(
  t: ReturnType<typeof setup>,
  owner: Id<"users">,
  overrides: JobOverrides = {},
) {
  return t.run((ctx) =>
    ctx.db.insert("jobs", {
      owner,
      kind: overrides.kind ?? "bulk",
      input: overrides.input ?? "someone",
      refresh: false,
      status: overrides.status ?? "queued",
      count: overrides.count ?? 0,
      attempt: overrides.attempt ?? 0,
      warnings: [],
      updatedAt: overrides.updatedAt ?? Date.now(),
      attemptStartedAt: overrides.attemptStartedAt,
      error: overrides.error,
      pages: overrides.pages,
      pageAttempt: overrides.pageAttempt,
      postsReceived: overrides.postsReceived,
      readyAt: overrides.readyAt,
      retryable: overrides.retryable,
      floorReached: overrides.floorReached,
      dismissedAt: overrides.dismissedAt,
      expectedUserId: overrides.expectedUserId,
    }),
  );
}

describe("convex/queue.ts timeline (operator Queue page)", () => {
  it("requires a signed-in caller", async () => {
    const t = setup();
    await expect(t.query(timeline, { now: Date.now() })).rejects.toThrow(
      "Sign in as an operator to import.",
    );
  });

  // Security finding (CodeRabbit, CWE-862 Missing Authorization): this used
  // to check only `user(ctx)`, which a signed-in-but-not-operator (including
  // an anonymous-session) caller satisfies — and this query returns shared
  // queue telemetry (job input, error, phase, account identity) that is not
  // meant to be public. `requireOperator` is the same boundary
  // `jobs.start`/`cancel`/`retry` already enforce.
  it("rejects a signed-in caller who is not an operator", async () => {
    const t = setup();
    const { a } = await withNonOperator(t);
    await expect(a.query(timeline, { now: Date.now() })).rejects.toThrow(
      "Sign in as an operator to import.",
    );
  });

  it("orders running first, then queued by readyAt ascending, then terminal-retryable last", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    const laterQueued = await seedJob(t, userId, {
      input: "later",
      status: "queued",
      readyAt: now + 60_000,
    });

    const running = await seedJob(t, userId, { input: "running-one", status: "running" });

    const soonerQueued = await seedJob(t, userId, {
      input: "sooner",
      status: "queued",
      readyAt: now + 5_000,
    });

    const readyNow = await seedJob(t, userId, { input: "ready-now", status: "queued" });

    const retryable = await seedJob(t, userId, {
      input: "stopped",
      status: "failed",
      retryable: true,
      updatedAt: now,
    });

    // `jobs.retry` accepts a cancelled job unconditionally (it is a
    // person's own choice to stop, never a permanent-failure verdict), so
    // it belongs in the terminal-retryable set too — CodeRabbit.
    const cancelled = await seedJob(t, userId, {
      input: "stopped-by-choice",
      status: "cancelled",
      updatedAt: now - 1_000,
    });

    // Not retryable — a permanent provider rejection — must be excluded.
    await seedJob(t, userId, { input: "dead", status: "failed", retryable: false });

    // Dismissed — hidden regardless of status.
    await seedJob(t, userId, {
      input: "cleared",
      status: "failed",
      retryable: true,
      dismissedAt: now,
    });

    const result = await a.query(timeline, { now });
    expect(result.truncated).toBe(false);
    expect(result.workerBusy).toBe(true);
    // Terminal-retryable jobs sort most-recently-stopped first: `retryable`
    // (updatedAt: now) ahead of `cancelled` (updatedAt: now - 1s).
    expect(result.entries.map((e) => e.jobId)).toEqual([
      running,
      readyNow,
      soonerQueued,
      laterQueued,
      retryable,
      cancelled,
    ]);
  });

  it("classifies the head of an idle queue as ready, and everything behind it as behind", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    await seedJob(t, userId, { input: "next", status: "queued" });
    await seedJob(t, userId, { input: "after", status: "queued", readyAt: now - 1 });

    const result = await a.query(timeline, { now });
    const byInput = new Map(result.entries.map((e) => [e.input, e]));
    // No job is running, so the head of the ready line is what the worker
    // claims on its very next poll.
    expect(byInput.get("next")?.waitReason).toEqual({ kind: "ready" });
    // "after" is due too, but "next" is ahead of it in claim order.
    expect(byInput.get("after")?.waitReason).toEqual({ kind: "behind", aheadCount: 1 });
  });

  it("classifies a queued job behind a running one, and one with a future readyAt as backoff", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    await seedJob(t, userId, { input: "r", status: "running" });
    await seedJob(t, userId, { input: "next", status: "queued" });
    await seedJob(t, userId, {
      input: "later",
      status: "queued",
      readyAt: now + 120_000,
    });

    const result = await a.query(timeline, { now });
    const byInput = new Map(result.entries.map((e) => [e.input, e]));
    expect(byInput.get("r")?.waitReason).toEqual({ kind: "running" });
    // The worker is busy, so even a due job is "behind" (behind the running
    // one), not "ready" — the worker will not touch it until that finishes.
    expect(byInput.get("next")?.waitReason).toEqual({ kind: "behind", aheadCount: 1 });
    expect(byInput.get("later")?.waitReason).toEqual({
      kind: "backoff",
      readyAt: now + 120_000,
    });
  });

  it("classifies a queued job as throttled when x.md's own reset time is still in the future", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();
    const resetAt = now + 30 * 60_000;

    await t.run((ctx) =>
      ctx.db.insert("providerThrottleEvents", {
        provider: "xmd",
        operation: "history",
        reason: "x.md rate limit reached.",
        // `remaining: 0` (exhausted, not merely unknown) is what makes
        // convex/limits.ts `activeThrottleUntil` treat `resetAt` as a real
        // blocking deadline rather than an allowance window that still has
        // capacity left — see that function's own doc comment.
        remaining: 0,
        resetAt,
        observedAt: now,
      }),
    );

    const readyJobId = await seedJob(t, userId, { input: "throttled-ready", status: "queued" });

    const backoffJobId = await seedJob(t, userId, {
      input: "throttled-backoff",
      status: "queued",
      readyAt: resetAt - 5_000,
    });

    const result = await a.query(timeline, { now });
    const byId = new Map(result.entries.map((e) => [e.jobId, e]));
    expect(byId.get(readyJobId)?.waitReason).toEqual({
      kind: "throttled",
      provider: "xmd",
      resetAt,
    });
    expect(byId.get(backoffJobId)?.waitReason).toEqual({
      kind: "throttled",
      provider: "xmd",
      resetAt,
    });
  });

  // CodeRabbit: a failed/partial/cancelled job is not queued at all — a
  // person must click Retry before anything happens to it — so it must
  // never read as "behind" (implies passive queueing) or "throttled"
  // (implies the scheduler is already going to act on it).
  it("gives terminal-but-retryable jobs their own needsRetry wait reason, never behind or throttled", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    const failedId = await seedJob(t, userId, { input: "failed", status: "failed" });

    const partialId = await seedJob(t, userId, {
      input: "partial",
      status: "partial",
      updatedAt: now - 1,
    });

    const cancelledId = await seedJob(t, userId, {
      input: "cancelled",
      status: "cancelled",
      updatedAt: now - 2,
    });

    const result = await a.query(timeline, { now });
    const byId = new Map(result.entries.map((e) => [e.jobId, e]));

    for (const id of [failedId, partialId, cancelledId])
      expect(byId.get(id)?.waitReason).toEqual({ kind: "needsRetry", throttledUntil: undefined });
  });

  it("carries the active x.md throttle onto a terminal-but-retryable job's needsRetry reason", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();
    const resetAt = now + 30 * 60_000;

    await t.run((ctx) =>
      ctx.db.insert("providerThrottleEvents", {
        provider: "xmd",
        operation: "history",
        reason: "x.md rate limit reached.",
        remaining: 0,
        resetAt,
        observedAt: now,
      }),
    );

    const failedId = await seedJob(t, userId, { input: "failed-throttled", status: "failed" });

    const result = await a.query(timeline, { now });
    const entry = result.entries.find((e) => e.jobId === failedId);
    expect(entry?.waitReason).toEqual({ kind: "needsRetry", throttledUntil: resetAt });
    // The ETA respects the throttle even though the wait reason is
    // "needsRetry", not "throttled" — retrying before `resetAt` would just
    // fail the same way again.
    expect(entry?.estimate.start).toBe(resetAt);
  });

  it("computes secondsPerPage/medianPages from the last completed bulk jobs and uses them for a queued job's ETA", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);

    // Five completed bulk jobs, each created at a well-separated instant
    // (so convex-test's monotonic _creationTime tie-breaker never nudges one
    // of them) with an exact (updatedAt - _creationTime) duration:
    // Their final attempts take 20, 20, 30, 20, and 20 seconds.
    // The first job spent an extra 100 seconds queued before its claim.
    // A fixed, far-future anchor rather than `Date.now()`: convex-test bumps
    // a document's `_creationTime` by +0.001ms whenever an insert's mocked
    // `Date.now()` collides with (or falls behind) the previous insert's
    // creation time, which a real-clock anchor risks colliding with
    // (e.g. the withOperator fixture's own insert above). A fixed future instant has no
    // such prior insert to collide with.
    const base = Date.UTC(2030, 0, 1);
    const base1 = base;
    const base2 = base + 10_000_000;
    const base3 = base + 20_000_000;

    try {
      vi.setSystemTime(base1);
      const doneOne = await seedJob(t, userId, { input: "done-1", status: "queued", pages: 5 });
      vi.setSystemTime(base1 + 100_000);
      await t.run((ctx) =>
        ctx.db.patch(doneOne, {
          status: "complete",
          attemptStartedAt: base1 + 80_000,
          updatedAt: base1 + 100_000,
        }),
      );

      vi.setSystemTime(base2);
      const doneTwo = await seedJob(t, userId, { input: "done-2", status: "queued", pages: 10 });
      vi.setSystemTime(base2 + 200_000);
      await t.run((ctx) =>
        ctx.db.patch(doneTwo, {
          status: "complete",
          attemptStartedAt: base2 + 180_000,
          updatedAt: base2 + 200_000,
        }),
      );

      vi.setSystemTime(base3);
      const doneThree = await seedJob(t, userId, { input: "done-3", status: "queued", pages: 2 });
      vi.setSystemTime(base3 + 60_000);
      await t.run((ctx) =>
        ctx.db.patch(doneThree, {
          status: "complete",
          attemptStartedAt: base3 + 30_000,
          updatedAt: base3 + 60_000,
        }),
      );

      for (let i = 0; i < 2; i++) {
        vi.setSystemTime(base3 + 100_000 + i * 100_000);
        await seedJob(t, userId, {
          input: `done-extra-${i}`,
          status: "complete",
          pages: 5,
          attemptStartedAt: Date.now() - 20_000,
        });
      }

      const now = base3 + 200_000;
      const queuedId = await seedJob(t, userId, { input: "next-up", status: "queued", pages: 2 });

      const result = await a.query(timeline, { now });
      expect(result.estimateInputs).toEqual({ secondsPerPage: 20, medianPages: 5, sampleSize: 5 });

      const entry = result.entries.find((e) => e.jobId === queuedId);
      // remaining pages = max(0, 5 - 2) = 3; own duration = 3 * 20s = 60s.
      expect(entry?.estimate.start).toBe(now);
      expect(entry?.estimate.finish).toBe(now + 60_000);
    } finally {
      vi.useRealTimers();
    }
  });

  it("requires five clean same-kind samples and excludes timeout and throttle runs", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    for (let i = 0; i < 4; i++)
      await seedJob(t, userId, {
        input: `clean-${i}`,
        status: "complete",
        kind: "live",
        pages: 1,
        attemptStartedAt: now - 20_000,
        updatedAt: now,
      });

    const timedOut = await seedJob(t, userId, {
      input: "timed-out",
      status: "complete",
      kind: "live",
      pages: 1,
      attemptStartedAt: now - 900_000,
      updatedAt: now,
      error: "provider_timeout",
    });

    const throttled = await seedJob(t, userId, {
      input: "throttled",
      status: "complete",
      kind: "live",
      pages: 1,
      attemptStartedAt: now - 900_000,
      updatedAt: now,
    });

    await t.run((ctx) =>
      ctx.db.insert("providerThrottleEvents", {
        jobId: throttled,
        provider: "xmd",
        operation: "history",
        reason: "rate limit",
        observedAt: now,
      }),
    );
    await seedJob(t, userId, {
      input: "wrong-kind",
      status: "complete",
      kind: "bulk",
      pages: 1,
      attemptStartedAt: now - 20_000,
      updatedAt: now,
    });
    const pending = await seedJob(t, userId, { input: "pending", kind: "live" });

    let result = await a.query(timeline, { now });
    expect(result.entries.find((e) => e.jobId === pending)?.estimate.measured).toBe(false);
    expect(result.estimateInputs.sampleSize).toBe(1);
    expect(timedOut).toBeDefined();

    await seedJob(t, userId, {
      input: "fifth",
      status: "complete",
      kind: "live",
      pages: 1,
      attemptStartedAt: now - 20_000,
      updatedAt: now,
    });
    result = await a.query(timeline, { now });
    const estimate = result.entries.find((e) => e.jobId === pending)?.estimate;
    expect(estimate).toMatchObject({ measured: true, start: now, finish: now + 20_000 });
  });

  it("finds completed samples behind more than 400 newer queued jobs", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    for (let i = 0; i < 5; i++)
      await seedJob(t, userId, {
        input: `sample-${i}`,
        status: "complete",
        pages: 1,
        attemptStartedAt: now - 20_000,
        updatedAt: now,
      });

    await t.run(async (ctx) => {
      for (let i = 0; i < 401; i++)
        await ctx.db.insert("jobs", {
          owner: userId,
          kind: "bulk",
          input: `queued-${i}`,
          refresh: false,
          status: "queued",
          count: 0,
          attempt: 0,
          warnings: [],
          updatedAt: now,
        });
    });

    const result = await a.query(timeline, { now });
    expect(result.estimateInputs).toEqual({ secondsPerPage: 20, medianPages: 1, sampleSize: 5 });
    expect(result.entries[0]?.estimate.measured).toBe(true);
  });

  it("chains a second queued job's start to the first job's estimated finish", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);

    // Fixed, far-future anchor — see the previous test's comment on why
    // `Date.now()` risks a `_creationTime` collision with the withOperator
    // fixture's own insert above.
    const start = Date.UTC(2031, 0, 1);

    try {
      vi.setSystemTime(start);
      const sample = await seedJob(t, userId, { input: "sample", status: "queued", pages: 4 });
      vi.setSystemTime(start + 80_000);
      await t.run((ctx) =>
        ctx.db.patch(sample, {
          status: "complete",
          attemptStartedAt: start + 60_000,
          updatedAt: start + 80_000,
        }),
      );

      for (let i = 0; i < 4; i++) {
        vi.setSystemTime(start + 100_000 + i * 100_000);
        await seedJob(t, userId, {
          input: `sample-${i}`,
          status: "complete",
          pages: 4,
          attemptStartedAt: Date.now() - 20_000,
        });
      }

      const now = start + 400_000;
      const first = await seedJob(t, userId, { input: "first", status: "queued", pages: 0 });

      const second = await seedJob(t, userId, {
        input: "second",
        status: "queued",
        readyAt: now + 1,
        pages: 0,
      });

      const result = await a.query(timeline, { now });
      const byId = new Map(result.entries.map((e) => [e.jobId, e]));
      const firstEntry = byId.get(first)!;
      const secondEntry = byId.get(second)!;
      // remaining = max(1, 4 - 0) = 4 pages * 20s = 80s.
      expect(firstEntry.estimate.finish).toBe(now + 80_000);
      // The second job cannot start before the first one is estimated to finish.
      expect(secondEntry.estimate.start).toBe(firstEntry.estimate.finish);
      expect(secondEntry.estimate.finish).toBe(firstEntry.estimate.finish + 80_000);
    } finally {
      vi.useRealTimers();
    }
  });

  // CodeRabbit: a running/queued bulk job whose OWN `pages` has already
  // caught up to (or passed) the recent median must still get at least one
  // remaining page — it is still going, not finished — or it would show
  // "download done ≈ now" while actively downloading, and every job behind
  // it in the chain would start too early.
  it("never estimates zero remaining pages for an unfinished bulk job, even past the recent median", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);

    const start = Date.UTC(2032, 0, 1);

    try {
      vi.setSystemTime(start);
      const sample = await seedJob(t, userId, { input: "sample", status: "queued", pages: 2 });
      vi.setSystemTime(start + 40_000);
      await t.run((ctx) =>
        ctx.db.patch(sample, {
          status: "complete",
          attemptStartedAt: start + 20_000,
          updatedAt: start + 40_000,
        }),
      );

      for (let i = 0; i < 4; i++) {
        vi.setSystemTime(start + 100_000 + i * 100_000);
        await seedJob(t, userId, {
          input: `sample-${i}`,
          status: "complete",
          pages: 2,
          attemptStartedAt: Date.now() - 20_000,
        });
      }

      const now = start + 400_000;

      // Already at the median (2 pages) but still running — not finished.
      const runningId = await seedJob(t, userId, {
        input: "big-account",
        status: "running",
        pages: 5,
      });

      const result = await a.query(timeline, { now });
      const entry = result.entries.find((e) => e.jobId === runningId);
      // Must be strictly after `now`, never `finish === start` ("done ≈ now").
      expect(entry?.estimate.finish).toBeGreaterThan(entry!.estimate.start);
      expect(entry?.estimate.finish).toBe(now + 20_000); // 1 page (the floor) * 20s.
    } finally {
      vi.useRealTimers();
    }
  });

  // /tmp/issues.md items 2/3: a deep-history backfill window job's own
  // `input` is a full `from:<handle> since:... until:...` search string, not
  // a bare handle, so resolving it the way every other job resolves account
  // identity (convex/lib/accounts.ts `jobIdentity`/`resolveAccount`, which
  // treats an unpinned job's `input` as a plain handle) never matched the
  // `by_handle` index — this timeline (and the account library) always
  // showed it with no account at all. `historyFor` (set by
  // convex/jobs.ts `insertHistoryWindowJob`) is now used directly instead.
  it("resolves a deep-history backfill window job to its account via historyFor, not by parsing its search-string input", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    const accountId: Id<"accounts"> = await t.run((ctx) =>
      ctx.db.insert("accounts", { handle: "theo", userId: "theo-provider-id", name: "Theo" }),
    );

    const windowJobId = await t.run((ctx) =>
      ctx.db.insert("jobs", {
        owner: userId,
        kind: "live",
        input: "from:theo since:2025-11-01 until:2025-12-01",
        since: "2025-11-01",
        until: "2025-12-01",
        origin: "history",
        historyFor: accountId,
        refresh: false,
        status: "running",
        count: 0,
        attempt: 1,
        warnings: [],
        postsReceived: 0,
        updatedAt: now,
      }),
    );

    const result = await a.query(timeline, { now });
    const entry = result.entries.find((e) => e.jobId === windowJobId);
    expect(entry?.account).toEqual({ accountId, handle: "theo", name: "Theo", avatar: undefined });
    expect(entry?.origin).toBe("history");
    expect(entry?.since).toBe("2025-11-01");
    expect(entry?.until).toBe("2025-12-01");
  });

  it("sets truncated when the whole-table scan hits its bound", async () => {
    const t = setup();
    const { a, userId } = await withOperator(t);
    const now = Date.now();

    // Insert more (non-candidate) jobs than QUEUE_SCAN_CAP so the scan
    // exhausts its bound before reaching the one queued job seeded first
    // (oldest -> scanned last, since the scan orders newest-first).
    const queuedId = await seedJob(t, userId, { input: "old-queued", status: "queued" });

    await t.run(async (ctx) => {
      for (let i = 0; i < 2_001; i++) {
        await ctx.db.insert("jobs", {
          owner: userId,
          kind: "live",
          input: `filler-${i}`,
          refresh: false,
          status: "complete",
          count: 0,
          attempt: 0,
          warnings: [],
          updatedAt: now,
        });
      }
    });

    const result = await a.query(timeline, { now });
    expect(result.truncated).toBe(true);
    expect(result.entries.some((e) => e.jobId === queuedId)).toBe(false);
  });
});
