import { describe, expect, it, vi } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import type { FunctionReference } from "convex/server";
import schema from "../convex/schema";
import type { Id } from "../convex/_generated/dataModel";
import type { Timeline } from "../convex/queue";

const modules = import.meta.glob("../convex/**/*.ts");

// convex/_generated/api.d.ts is a build artifact regenerated by
// `npx convex dev`/`convex codegen` and does not yet know about
// convex/queue.ts — same situation as convex/summary.ts and convex/limits.ts
// (see their own test files' header comments); `anyApi` resolves to the
// exact same function reference at runtime as the generated `api` object
// would once codegen has run.
// SAFETY: `anyApi.queue.timeline` is `FunctionReference<any, any>` only
// because codegen hasn't caught up (see above); convex-test rejects the
// reference outright if `convex/queue.ts` did not actually register a
// `timeline` query, so this narrowing to its real, frozen signature is
// checked at every test run, not merely asserted away.
const timeline = anyApi.queue.timeline as FunctionReference<
  "query",
  "public",
  { now: number },
  Timeline
>;

function setup() {
  return convexTest(schema, modules);
}

async function withUser(t: ReturnType<typeof setup>) {
  const userId: Id<"users"> = await t.run((ctx) => ctx.db.insert("users", { isAnonymous: true }));

  return { a: t.withIdentity({ subject: `${userId}|session` }), userId };
}

type JobOverrides = Partial<{
  kind: "bulk" | "live" | "post" | "profile" | "following" | "followers" | "archive";
  input: string;
  status: "queued" | "running" | "complete" | "partial" | "failed" | "cancelled";
  count: number;
  attempt: number;
  pages: number;
  pageAttempt: number;
  postsReceived: number;
  readyAt: number;
  retryable: boolean;
  floorReached: boolean;
  updatedAt: number;
  dismissedAt: number;
  expectedUserId: string;
}>;

async function seedJob(
  t: ReturnType<typeof setup>,
  owner: Id<"users">,
  overrides: JobOverrides = {},
) {
  return t.run((ctx) =>
    ctx.db.insert("jobs", {
      owner,
      kind: overrides.kind ?? "bulk",
      input: overrides.input ?? "someone",
      refresh: false,
      status: overrides.status ?? "queued",
      count: overrides.count ?? 0,
      attempt: overrides.attempt ?? 0,
      warnings: [],
      updatedAt: overrides.updatedAt ?? Date.now(),
      pages: overrides.pages,
      pageAttempt: overrides.pageAttempt,
      postsReceived: overrides.postsReceived,
      readyAt: overrides.readyAt,
      retryable: overrides.retryable,
      floorReached: overrides.floorReached,
      dismissedAt: overrides.dismissedAt,
      expectedUserId: overrides.expectedUserId,
    }),
  );
}

describe("convex/queue.ts timeline (operator Queue page)", () => {
  it("requires a signed-in caller", async () => {
    const t = setup();
    await expect(t.query(timeline, { now: Date.now() })).rejects.toThrow(
      "Start a session to use your workspace.",
    );
  });

  it("orders running first, then queued by readyAt ascending, then terminal-retryable last", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);
    const now = Date.now();

    const laterQueued = await seedJob(t, userId, {
      input: "later",
      status: "queued",
      readyAt: now + 60_000,
    });

    const running = await seedJob(t, userId, { input: "running-one", status: "running" });

    const soonerQueued = await seedJob(t, userId, {
      input: "sooner",
      status: "queued",
      readyAt: now + 5_000,
    });

    const readyNow = await seedJob(t, userId, { input: "ready-now", status: "queued" });

    const retryable = await seedJob(t, userId, {
      input: "stopped",
      status: "failed",
      retryable: true,
    });

    // Not retryable — a permanent provider rejection — must be excluded.
    await seedJob(t, userId, { input: "dead", status: "failed", retryable: false });

    // Dismissed — hidden regardless of status.
    await seedJob(t, userId, {
      input: "cleared",
      status: "failed",
      retryable: true,
      dismissedAt: now,
    });

    const result = await a.query(timeline, { now });
    expect(result.truncated).toBe(false);
    expect(result.workerBusy).toBe(true);
    expect(result.entries.map((e) => e.jobId)).toEqual([
      running,
      readyNow,
      soonerQueued,
      laterQueued,
      retryable,
    ]);
  });

  it("classifies the head of an idle queue as ready, and everything behind it as behind", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);
    const now = Date.now();

    await seedJob(t, userId, { input: "next", status: "queued" });
    await seedJob(t, userId, { input: "after", status: "queued", readyAt: now - 1 });

    const result = await a.query(timeline, { now });
    const byInput = new Map(result.entries.map((e) => [e.input, e]));
    // No job is running, so the head of the ready line is what the worker
    // claims on its very next poll.
    expect(byInput.get("next")?.waitReason).toEqual({ kind: "ready" });
    // "after" is due too, but "next" is ahead of it in claim order.
    expect(byInput.get("after")?.waitReason).toEqual({ kind: "behind", aheadCount: 1 });
  });

  it("classifies a queued job behind a running one, and one with a future readyAt as backoff", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);
    const now = Date.now();

    await seedJob(t, userId, { input: "r", status: "running" });
    await seedJob(t, userId, { input: "next", status: "queued" });
    await seedJob(t, userId, {
      input: "later",
      status: "queued",
      readyAt: now + 120_000,
    });

    const result = await a.query(timeline, { now });
    const byInput = new Map(result.entries.map((e) => [e.input, e]));
    expect(byInput.get("r")?.waitReason).toEqual({ kind: "running" });
    // The worker is busy, so even a due job is "behind" (behind the running
    // one), not "ready" — the worker will not touch it until that finishes.
    expect(byInput.get("next")?.waitReason).toEqual({ kind: "behind", aheadCount: 1 });
    expect(byInput.get("later")?.waitReason).toEqual({
      kind: "backoff",
      readyAt: now + 120_000,
    });
  });

  it("classifies a queued job as throttled when x.md's own reset time is still in the future", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);
    const now = Date.now();
    const resetAt = now + 30 * 60_000;

    await t.run((ctx) =>
      ctx.db.insert("providerThrottleEvents", {
        provider: "xmd",
        operation: "history",
        reason: "x.md rate limit reached.",
        // `remaining: 0` (exhausted, not merely unknown) is what makes
        // convex/limits.ts `activeThrottleUntil` treat `resetAt` as a real
        // blocking deadline rather than an allowance window that still has
        // capacity left — see that function's own doc comment.
        remaining: 0,
        resetAt,
        observedAt: now,
      }),
    );

    const readyJobId = await seedJob(t, userId, { input: "throttled-ready", status: "queued" });

    const backoffJobId = await seedJob(t, userId, {
      input: "throttled-backoff",
      status: "queued",
      readyAt: resetAt - 5_000,
    });

    const result = await a.query(timeline, { now });
    const byId = new Map(result.entries.map((e) => [e.jobId, e]));
    expect(byId.get(readyJobId)?.waitReason).toEqual({
      kind: "throttled",
      provider: "xmd",
      resetAt,
    });
    expect(byId.get(backoffJobId)?.waitReason).toEqual({
      kind: "throttled",
      provider: "xmd",
      resetAt,
    });
  });

  it("computes secondsPerPage/medianPages from the last completed bulk jobs and uses them for a queued job's ETA", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);

    // Three completed bulk jobs, each created at a well-separated instant
    // (so convex-test's monotonic _creationTime tie-breaker never nudges one
    // of them) with an exact (updatedAt - _creationTime) duration:
    // 100s/5 pages = 20s/page, 200s/10 = 20s/page, 60s/2 = 30s/page ->
    // median seconds/page = 20, median pages = 5.
    // A fixed, far-future anchor rather than `Date.now()`: convex-test bumps
    // a document's `_creationTime` by +0.001ms whenever an insert's mocked
    // `Date.now()` collides with (or falls behind) the previous insert's
    // creation time, which a real-clock anchor risks colliding with
    // (e.g. the `withUser` insert above). A fixed future instant has no
    // such prior insert to collide with.
    const base = Date.UTC(2030, 0, 1);
    const base1 = base;
    const base2 = base + 10_000_000;
    const base3 = base + 20_000_000;

    try {
      vi.setSystemTime(base1);
      const doneOne = await seedJob(t, userId, { input: "done-1", status: "queued", pages: 5 });
      vi.setSystemTime(base1 + 100_000);
      await t.run((ctx) =>
        ctx.db.patch(doneOne, { status: "complete", updatedAt: base1 + 100_000 }),
      );

      vi.setSystemTime(base2);
      const doneTwo = await seedJob(t, userId, { input: "done-2", status: "queued", pages: 10 });
      vi.setSystemTime(base2 + 200_000);
      await t.run((ctx) =>
        ctx.db.patch(doneTwo, { status: "complete", updatedAt: base2 + 200_000 }),
      );

      vi.setSystemTime(base3);
      const doneThree = await seedJob(t, userId, { input: "done-3", status: "queued", pages: 2 });
      vi.setSystemTime(base3 + 60_000);
      await t.run((ctx) =>
        ctx.db.patch(doneThree, { status: "complete", updatedAt: base3 + 60_000 }),
      );

      const now = base3 + 60_000;
      const queuedId = await seedJob(t, userId, { input: "next-up", status: "queued", pages: 2 });

      const result = await a.query(timeline, { now });
      expect(result.estimateInputs).toEqual({ secondsPerPage: 20, medianPages: 5, sampleSize: 3 });

      const entry = result.entries.find((e) => e.jobId === queuedId);
      // remaining pages = max(0, 5 - 2) = 3; own duration = 3 * 20s = 60s.
      expect(entry?.estimate.start).toBe(now);
      expect(entry?.estimate.finish).toBe(now + 60_000);
    } finally {
      vi.useRealTimers();
    }
  });

  it("chains a second queued job's start to the first job's estimated finish", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);

    // Fixed, far-future anchor — see the previous test's comment on why
    // `Date.now()` risks a `_creationTime` collision with the `withUser`
    // insert above.
    const start = Date.UTC(2031, 0, 1);

    try {
      vi.setSystemTime(start);
      const sample = await seedJob(t, userId, { input: "sample", status: "queued", pages: 4 });
      vi.setSystemTime(start + 80_000); // 20s/page over 4 pages
      await t.run((ctx) => ctx.db.patch(sample, { status: "complete", updatedAt: start + 80_000 }));

      const now = start + 80_000;
      const first = await seedJob(t, userId, { input: "first", status: "queued", pages: 0 });

      const second = await seedJob(t, userId, {
        input: "second",
        status: "queued",
        readyAt: now + 1,
        pages: 0,
      });

      const result = await a.query(timeline, { now });
      const byId = new Map(result.entries.map((e) => [e.jobId, e]));
      const firstEntry = byId.get(first)!;
      const secondEntry = byId.get(second)!;
      // remaining = max(0, 4 - 0) = 4 pages * 20s = 80s.
      expect(firstEntry.estimate.finish).toBe(now + 80_000);
      // The second job cannot start before the first one is estimated to finish.
      expect(secondEntry.estimate.start).toBe(firstEntry.estimate.finish);
      expect(secondEntry.estimate.finish).toBe(firstEntry.estimate.finish + 80_000);
    } finally {
      vi.useRealTimers();
    }
  });

  it("sets truncated when the whole-table scan hits its bound", async () => {
    const t = setup();
    const { a, userId } = await withUser(t);
    const now = Date.now();

    // Insert more (non-candidate) jobs than QUEUE_SCAN_CAP so the scan
    // exhausts its bound before reaching the one queued job seeded first
    // (oldest -> scanned last, since the scan orders newest-first).
    const queuedId = await seedJob(t, userId, { input: "old-queued", status: "queued" });

    await t.run(async (ctx) => {
      for (let i = 0; i < 2_001; i++) {
        await ctx.db.insert("jobs", {
          owner: userId,
          kind: "live",
          input: `filler-${i}`,
          refresh: false,
          status: "complete",
          count: 0,
          attempt: 0,
          warnings: [],
          updatedAt: now,
        });
      }
    });

    const result = await a.query(timeline, { now });
    expect(result.truncated).toBe(true);
    expect(result.entries.some((e) => e.jobId === queuedId)).toBe(false);
  });
});
