import { afterEach, describe, expect, it, vi } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import type { FunctionReference } from "convex/server";
import schema from "../convex/schema";
import type { ServiceStatus } from "../convex/summary";

const modules = import.meta.glob("../convex/**/*.ts");

// `anyApi` rather than the generated `api`/`internal`: convex/_generated/
// api.d.ts is a build artifact regenerated by `npx convex dev`/`convex
// codegen` (both of which talk to the deployment) and does not know about
// convex/health.ts. It resolves to the same function references at runtime —
// see convex/publication.ts's header and tests/publication.test.ts.
const recordHealth = anyApi.health.record;
const probeSearch = anyApi.health.probeSearch;
const workerPoll = anyApi.worker.poll;
// summary.health is the existing, already-correct READ side; it is called
// here unmodified, to prove the rows this unit writes are what the dashboard
// actually ends up saying.
const healthQuery = anyApi.summary.health as unknown as FunctionReference<
  "query",
  "public",
  { now: number },
  ServiceStatus[]
>;

afterEach(() => {
  vi.unstubAllEnvs();
  vi.unstubAllGlobals();
});

function setup() {
  return convexTest(schema, modules);
}

async function authenticated(t: ReturnType<typeof setup>) {
  const userId = await t.run((ctx) => ctx.db.insert("users", { isAnonymous: true }));
  return t.withIdentity({ subject: `${userId}|session` });
}

function rows(t: ReturnType<typeof setup>) {
  return t.run((ctx) => ctx.db.query("serviceHealth").collect());
}

function report(body: unknown, token = "secret") {
  return {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify(body),
  };
}

function healthReport(overrides: Record<string, unknown> = {}) {
  return {
    version: 1 as const,
    service: "indexer" as const,
    healthy: true,
    observedAt: Date.now(),
    ...overrides,
  };
}

/** Let the wall clock advance so "this reading is newer than that one" is a
 * real comparison rather than a same-millisecond coincidence. */
function tick() {
  return new Promise((resolve) => setTimeout(resolve, 5));
}

describe("service health reporting (POST /service/health, convex/health.ts)", () => {
  describe("auth — fails closed", () => {
    it("rejects an unauthenticated report with 401 and writes nothing", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      const res = await t.fetch("/service/health", report(healthReport(), "wrong"));
      expect(res.status).toBe(401);
      expect(await rows(t)).toEqual([]);
    });

    it("rejects a report with no Authorization header at all", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      const res = await t.fetch("/service/health", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(healthReport()),
      });
      expect(res.status).toBe(401);
      expect(await rows(t)).toEqual([]);
    });

    it("fails closed with 401 when no health token is configured at all", async () => {
      // An unconfigured receiver is never an open one: with nothing to
      // compare against, every report is rejected rather than accepted.
      const t = setup();
      const res = await t.fetch("/service/health", report(healthReport(), "anything"));
      expect(res.status).toBe(401);
      expect(await rows(t)).toEqual([]);
    });

    it("supports the legacy DATA_SERVICE_TOKEN fallback like the other service capabilities", async () => {
      const t = setup();
      vi.stubEnv("DATA_SERVICE_TOKEN", "legacy");
      const res = await t.fetch("/service/health", report(healthReport(), "legacy"));
      expect(res.status).toBe(200);
      expect(await rows(t)).toHaveLength(1);
    });

    it("does not accept the legacy token once a dedicated one is configured", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      vi.stubEnv("DATA_SERVICE_TOKEN", "legacy");
      const res = await t.fetch("/service/health", report(healthReport(), "legacy"));
      expect(res.status).toBe(401);
      expect(await rows(t)).toEqual([]);
    });
  });

  describe("body narrowing", () => {
    it("rejects a body that is not a health report with 400", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      expect((await t.fetch("/service/health", report({ foo: "bar" }))).status).toBe(400);
      expect(
        (await t.fetch("/service/health", report(healthReport({ service: "nope" })))).status,
      ).toBe(400);
      expect(
        (await t.fetch("/service/health", report(healthReport({ healthy: "yes" })))).status,
      ).toBe(400);
      expect(await rows(t)).toEqual([]);
    });

    it("rejects an otherwise well-formed body carrying an unknown extra field", async () => {
      // The strict Convex validator behind this route throws on an unlisted
      // key; whitelisting here is what keeps that a documented 400 instead
      // of an uncaught 500.
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      const res = await t.fetch(
        "/service/health",
        report({ ...healthReport(), debugExtra: "should never reach record" }),
      );
      expect(res.status).toBe(400);
      expect(await rows(t)).toEqual([]);
    });

    it("rejects an unhealthy report that does not say what went wrong", async () => {
      // `lastError` is supposed to carry the real failure text. A bare
      // `healthy: false` the dashboard cannot explain is worse than none.
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      const res = await t.fetch("/service/health", report(healthReport({ healthy: false })));
      expect(res.status).toBe(400);
      expect(await rows(t)).toEqual([]);
    });
  });

  describe("the row it writes", () => {
    it("inserts on the first report and patches the same row afterwards — one row per service", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      expect((await t.fetch("/service/health", report(healthReport()))).status).toBe(200);
      const [inserted] = await rows(t);
      expect(inserted).toMatchObject({ service: "indexer", healthy: true });

      await tick();
      expect((await t.fetch("/service/health", report(healthReport()))).status).toBe(200);
      expect((await t.fetch("/service/health", report(healthReport()))).status).toBe(200);
      const after = await rows(t);
      expect(after).toHaveLength(1);
      // Same document, not a delete-and-reinsert and not an accumulating log.
      expect(after[0]._id).toBe(inserted._id);
      expect(after[0].observedAt).toBeGreaterThan(inserted.observedAt);
    });

    it("keeps one row per service, not one row per reporter", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      await t.fetch("/service/health", report(healthReport({ service: "indexer" })));
      await t.fetch("/service/health", report(healthReport({ service: "receiver" })));
      await t.fetch("/service/health", report(healthReport({ service: "indexer" })));
      const all = await rows(t);
      expect(all).toHaveLength(2);
      expect(all.map((row) => row.service).sort()).toEqual(["indexer", "receiver"]);
    });

    it("stamps lastSuccessAt only from an observed success", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      await t.fetch("/service/health", report(healthReport()));
      const [row] = await rows(t);
      expect(row.healthy).toBe(true);
      expect(row.lastSuccessAt).toBe(row.observedAt);
      expect(row.lastHeartbeatAt).toBe(row.observedAt);
      expect(row.lastError).toBeUndefined();
    });

    it("a failure preserves the previous lastSuccessAt while setting healthy:false and the real error text", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      await t.fetch("/service/health", report(healthReport()));
      const [healthyRow] = await rows(t);
      const lastSuccessAt = healthyRow.lastSuccessAt;
      expect(lastSuccessAt).toBeDefined();

      await tick();
      const failedAt = Date.now();
      const res = await t.fetch(
        "/service/health",
        report(
          healthReport({
            healthy: false,
            observedAt: failedAt,
            error: { message: "index open failed: Permission denied (os error 13)" },
          }),
        ),
      );
      expect(res.status).toBe(200);

      const after = await rows(t);
      expect(after).toHaveLength(1);
      expect(after[0]).toMatchObject({
        healthy: false,
        // Verbatim, not rewritten into a friendlier sentence.
        lastError: {
          message: "index open failed: Permission denied (os error 13)",
          observedAt: failedAt,
        },
      });
      // The evidence that it worked at some point survives the failure.
      expect(after[0].lastSuccessAt).toBe(lastSuccessAt);
      expect(after[0].observedAt).toBeGreaterThan(lastSuccessAt!);
    });

    it("a later success does not erase the last error, and flips healthy back", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      await t.fetch(
        "/service/health",
        report(healthReport({ healthy: false, error: { message: "connection refused" } })),
      );
      const [failedRow] = await rows(t);
      expect(failedRow.lastSuccessAt).toBeUndefined();

      await tick();
      await t.fetch("/service/health", report(healthReport()));
      const [row] = await rows(t);
      expect(row.healthy).toBe(true);
      expect(row.lastSuccessAt).toBe(row.observedAt);
      // Sticky, exactly like convex/publication.ts's lastError: `healthy`
      // plus the timestamps say whether it is current or history.
      expect(row.lastError?.message).toBe("connection refused");
    });

    it("uses the deployment's clock for the row, so a skewed reporter cannot forge freshness", async () => {
      const t = setup();
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      const wayInTheFuture = Date.now() + 10 * 365 * 24 * 60 * 60 * 1000;
      await t.fetch(
        "/service/health",
        report(
          healthReport({
            healthy: false,
            observedAt: wayInTheFuture,
            error: { message: "clock is wrong" },
          }),
        ),
      );
      const [row] = await rows(t);
      expect(row.observedAt).toBeLessThan(wayInTheFuture);
      expect(row.lastHeartbeatAt).toBeLessThan(wayInTheFuture);
      // The reporter's own account of when it saw the error is still kept
      // verbatim next to the message — it just cannot drive staleness.
      expect(row.lastError?.observedAt).toBe(wayInTheFuture);
    });
  });

  describe("what the dashboard ends up saying (convex/summary.ts's health query, unmodified)", () => {
    it("a service that never reported still reads unknown — nothing is seeded", async () => {
      const t = setup();
      const a = await authenticated(t);
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      // Configuration alone must never produce a row.
      vi.stubEnv("SEARCH_API_URL", "https://search.example/search");
      vi.stubEnv("RAW_CAPTURE_URL", "https://capture.example/captures");
      expect(await rows(t)).toEqual([]);
      expect(await a.query(healthQuery, { now: Date.now() })).toEqual([
        { service: "indexer", kind: "unknown" },
        { service: "receiver", kind: "unknown" },
        { service: "search", kind: "unknown" },
      ]);
    });

    it("a reported service reads as a known, fresh reading while the others stay unknown", async () => {
      const t = setup();
      const a = await authenticated(t);
      vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
      await t.fetch("/service/health", report(healthReport({ service: "indexer" })));
      const result = await a.query(healthQuery, { now: Date.now() });
      const byService = new Map(result.map((status) => [status.service, status]));
      expect(byService.get("indexer")).toMatchObject({
        kind: "known",
        healthy: true,
        stale: false,
      });
      expect(byService.get("receiver")).toEqual({ service: "receiver", kind: "unknown" });
      expect(byService.get("search")).toEqual({ service: "search", kind: "unknown" });
    });
  });
});

describe("search service probe (convex/health.ts probeSearch, scheduled in convex/crons.ts)", () => {
  it("records nothing when SEARCH_API_URL is unset — unconfigured is not unhealthy", async () => {
    const t = setup();
    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);
    await t.action(probeSearch, {});
    expect(fetchSpy).not.toHaveBeenCalled();
    expect(await rows(t)).toEqual([]);
  });

  it("records nothing when SEARCH_API_URL cannot be parsed — our misconfiguration is not the service's fault", async () => {
    const t = setup();
    vi.stubEnv("SEARCH_API_URL", "not a url");
    const fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);
    await t.action(probeSearch, {});
    expect(fetchSpy).not.toHaveBeenCalled();
    expect(await rows(t)).toEqual([]);
  });

  it("derives /health from SEARCH_API_URL's origin rather than hardcoding a host", async () => {
    const t = setup();
    vi.stubEnv("SEARCH_API_URL", "https://search.example:4321/search");
    let requested: string | undefined;
    vi.stubGlobal("fetch", async (input: string | URL | Request) => {
      requested = typeof input === "string" ? input : input.toString();
      return new Response("ok", { status: 200 });
    });
    await t.action(probeSearch, {});
    // Port included: the search service is separately owned and moves.
    expect(requested).toBe("https://search.example:4321/health");
  });

  it("records a real success, with lastSuccessAt, only when the service answers ok", async () => {
    const t = setup();
    vi.stubEnv("SEARCH_API_URL", "https://search.example/search");
    vi.stubGlobal("fetch", async () => new Response("ok\n", { status: 200 }));
    await t.action(probeSearch, {});
    const [row] = await rows(t);
    expect(row).toMatchObject({ service: "search", healthy: true });
    expect(row.lastSuccessAt).toBe(row.observedAt);
  });

  it("records the transport's own words on failure, and keeps the earlier success", async () => {
    const t = setup();
    vi.stubEnv("SEARCH_API_URL", "https://search.example/search");
    vi.stubGlobal("fetch", async () => new Response("ok", { status: 200 }));
    await t.action(probeSearch, {});
    const [healthyRow] = await rows(t);
    const lastSuccessAt = healthyRow.lastSuccessAt;

    await tick();
    vi.stubGlobal("fetch", () => Promise.reject(new Error("connect ECONNREFUSED 10.0.0.1:4321")));
    await t.action(probeSearch, {});
    const after = await rows(t);
    expect(after).toHaveLength(1);
    expect(after[0].healthy).toBe(false);
    expect(after[0].lastError?.message).toBe("connect ECONNREFUSED 10.0.0.1:4321");
    expect(after[0].lastSuccessAt).toBe(lastSuccessAt);
  });

  it("does not call a 200 from something that is not the search service healthy", async () => {
    const t = setup();
    vi.stubEnv("SEARCH_API_URL", "https://search.example/search");
    vi.stubGlobal(
      "fetch",
      async () => new Response("<html>502 Bad Gateway</html>", { status: 200 }),
    );
    await t.action(probeSearch, {});
    const [row] = await rows(t);
    expect(row.healthy).toBe(false);
    expect(row.lastError?.message).toContain("502 Bad Gateway");
    expect(row.lastSuccessAt).toBeUndefined();
  });

  it("records a non-2xx as unhealthy with the status it actually saw", async () => {
    const t = setup();
    vi.stubEnv("SEARCH_API_URL", "https://search.example/search");
    vi.stubGlobal("fetch", async () => new Response("nope", { status: 503 }));
    await t.action(probeSearch, {});
    const [row] = await rows(t);
    expect(row.healthy).toBe(false);
    expect(row.lastError?.message).toContain("503");
  });
});

describe("capture-receiver health via the production worker (convex/worker.ts poll)", () => {
  function outbound() {
    vi.stubEnv("COLLECTOR_MODE", "outbound");
    vi.stubEnv("COLLECTOR_TOKEN", "test-worker-secret");
  }

  it("records what the worker observed about the loopback receiver", async () => {
    const t = setup();
    outbound();
    await t.action(workerPoll, {
      token: "test-worker-secret",
      online: true,
      receiver: { healthy: true },
    });
    const [row] = await rows(t);
    expect(row).toMatchObject({ service: "receiver", healthy: true });
    expect(row.lastSuccessAt).toBe(row.observedAt);
  });

  it("carries the receiver's real failure text and keeps the earlier success", async () => {
    const t = setup();
    outbound();
    await t.action(workerPoll, {
      token: "test-worker-secret",
      online: true,
      receiver: { healthy: true },
    });
    const [healthyRow] = await rows(t);
    const lastSuccessAt = healthyRow.lastSuccessAt;

    await tick();
    await t.action(workerPoll, {
      token: "test-worker-secret",
      online: false,
      heartbeatOnly: true,
      receiver: { healthy: false, error: "Capture receiver answered HTTP 503." },
    });
    const after = await rows(t);
    expect(after).toHaveLength(1);
    expect(after[0].healthy).toBe(false);
    expect(after[0].lastError?.message).toBe("Capture receiver answered HTTP 503.");
    expect(after[0].lastSuccessAt).toBe(lastSuccessAt);
  });

  it("says nothing about the receiver when the worker did not probe it", async () => {
    // The worker's shutdown poll reports `online: false` about itself only.
    const t = setup();
    outbound();
    await t.action(workerPoll, {
      token: "test-worker-secret",
      heartbeatOnly: true,
      online: false,
    });
    expect(await rows(t)).toEqual([]);
  });

  it("writes no health row when the worker is not authenticated", async () => {
    const t = setup();
    outbound();
    await expect(
      t.action(workerPoll, { token: "wrong", receiver: { healthy: true } }),
    ).rejects.toThrow("authentication failed");
    expect(await rows(t)).toEqual([]);
  });

  it("is an observation only: reporting health never moves a job's status", async () => {
    const t = setup();
    outbound();
    const { owner, jobId } = await t.run(async (ctx) => {
      const owner = await ctx.db.insert("users", { isAnonymous: true });
      const jobId = await ctx.db.insert("jobs", {
        owner,
        kind: "bulk",
        input: "alice",
        status: "complete",
        count: 5,
        attempt: 1,
        refresh: false,
        warnings: [],
        updatedAt: 0,
      });
      return { owner, jobId };
    });
    expect(owner).toBeDefined();
    await t.action(workerPoll, {
      token: "test-worker-secret",
      heartbeatOnly: true,
      online: true,
      receiver: { healthy: false, error: "fetch failed" },
    });
    const job = await t.run((ctx) => ctx.db.get(jobId));
    expect(job).toMatchObject({ status: "complete", attempt: 1, updatedAt: 0 });
    expect(await rows(t)).toHaveLength(1);
  });
});

describe("the internal upsert itself (convex/health.ts record)", () => {
  it("never derives health from configuration — only a caller's observation writes a row", async () => {
    const t = setup();
    vi.stubEnv("SEARCH_API_URL", "https://search.example/search");
    vi.stubEnv("SERVICE_HEALTH_TOKEN", "secret");
    vi.stubEnv("COLLECTOR_MODE", "outbound");
    expect(await rows(t)).toEqual([]);
    await t.mutation(recordHealth, { service: "search", healthy: true });
    expect(await rows(t)).toHaveLength(1);
  });

  it("truncates a runaway error message visibly rather than silently", async () => {
    const t = setup();
    await t.mutation(recordHealth, {
      service: "indexer",
      healthy: false,
      error: { message: "x".repeat(5000), observedAt: Date.now() },
    });
    const [row] = await rows(t);
    expect(row.lastError?.message).toContain("(truncated)");
    expect(row.lastError?.message.length).toBeLessThan(1100);
  });
});
