import { describe, expect, it } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import schema from "../convex/schema";
import type { Id } from "../convex/_generated/dataModel";
import type { DashboardSummary, AccountLibraryRow } from "../convex/lib/contracts";
import type { ServiceStatus } from "../convex/summary";

const modules = import.meta.glob("../convex/**/*.ts");

// convex/_generated/api.d.ts is a build artifact regenerated by
// `npx convex dev`/`convex codegen` (both of which talk to the deployment)
// and does not yet know about convex/summary.ts — see convex/publication.ts's
// header comment for why `anyApi` (convex/server) is used instead of the
// generated `api` object here; it resolves to the exact same function
// references at runtime.
// Both queries require `now` as an argument (convex/summary.ts: neither
// reads the wall clock internally any more — convex/_generated/ai/
// guidelines.md "Do not read the wall clock inside a query"), so every call
// below passes it explicitly. Calling `Date.now()` here, in test code that
// builds the query's args, is exactly the sanctioned pattern ("pass the
// current time in as an argument") — it is not a wall-clock read inside a
// query handler.
// SAFETY: `anyApi.summary.summary` is typed as `FunctionReference<any, any, any, any>`
// (convex/server's untyped API-builder), so every field it carries is `any`
// and a single assertion to the concrete signature below is a narrowing
// TypeScript already allows structurally — verified at the call site because
// convex-test rejects the reference outright if the module/function name it
// resolves to does not actually exist.
const summaryQuery = anyApi.summary.summary as import("convex/server").FunctionReference<
  "query",
  "public",
  { now: number },
  DashboardSummary
>;

// SAFETY: same `anyApi` `any`-typed reference as `summaryQuery` above.
const healthQuery = anyApi.summary.health as import("convex/server").FunctionReference<
  "query",
  "public",
  { now: number },
  ServiceStatus[]
>;

// convex/library.ts's `rows` — not owned by this unit, but read here
// (unmodified) to prove how summary.summary's global indexedAccounts/
// indexedPosts relate to the shared account list every caller sees.
const libraryRowsQuery = anyApi.library
  .rows as unknown as import("convex/server").FunctionReference<
  "query",
  "public",
  { search?: string; status?: string },
  { rows: AccountLibraryRow[]; truncated: boolean }
>;

async function setup() {
  const t = convexTest(schema, modules);

  const [alice, bob] = await t.run(async (ctx) => [
    await ctx.db.insert("users", { isAnonymous: true }),
    await ctx.db.insert("users", { isAnonymous: true }),
  ]);

  return {
    t,
    alice,
    bob,
    a: t.withIdentity({ subject: `${alice}|session` }),
    b: t.withIdentity({ subject: `${bob}|session` }),
  };
}

type Kind = "bulk" | "live" | "post" | "profile" | "following" | "followers" | "archive";

type Status = "queued" | "running" | "complete" | "partial" | "failed" | "cancelled";

type PublicationState =
  | "downloaded"
  | "waiting_for_indexing"
  | "indexing"
  | "searchable"
  | "failed";

async function insertAccount(
  t: Awaited<ReturnType<typeof setup>>["t"],
  args: { handle: string; userId: string; name?: string },
) {
  return t.run((ctx) =>
    ctx.db.insert("accounts", {
      handle: args.handle,
      userId: args.userId,
      name: args.name ?? args.handle,
    }),
  );
}

async function insertJob(
  t: Awaited<ReturnType<typeof setup>>["t"],
  owner: Id<"users">,
  args: {
    kind?: Kind;
    input: string;
    expectedUserId?: string;
    status?: Status;
    count?: number;
    updatedAt?: number;
  },
) {
  return t.run((ctx) =>
    ctx.db.insert("jobs", {
      owner,
      kind: args.kind ?? "bulk",
      input: args.input,
      expectedUserId: args.expectedUserId,
      refresh: false,
      status: args.status ?? "complete",
      count: args.count ?? 0,
      attempt: 1,
      warnings: [],
      updatedAt: args.updatedAt ?? Date.now(),
    }),
  );
}

async function insertPublication(
  t: Awaited<ReturnType<typeof setup>>["t"],
  args: {
    accountId: Id<"accounts">;
    state: PublicationState;
    committedGeneration?: number;
    searchablePostCount?: number;
  },
) {
  return t.run((ctx) =>
    ctx.db.insert("accountPublications", {
      accountId: args.accountId,
      state: args.state,
      committedGeneration: args.committedGeneration ?? 1,
      searchablePostCount: args.searchablePostCount,
      updatedAt: Date.now(),
    }),
  );
}

async function insertReceipt(
  t: Awaited<ReturnType<typeof setup>>["t"],
  args: { jobId: Id<"jobs">; captureId: string; receiptId?: string; records?: number },
) {
  return t.run((ctx) =>
    ctx.db.insert("receipts", {
      jobId: args.jobId,
      captureId: args.captureId,
      receiptId: args.receiptId ?? args.captureId,
      records: args.records ?? 1,
    }),
  );
}

async function insertPublicationUpdate(
  t: Awaited<ReturnType<typeof setup>>["t"],
  args: {
    accountId: Id<"accounts">;
    handle: string;
    captureIds: string[];
    generation: number;
    outcome:
      | "applied"
      | "stale_ignored"
      | "duplicate_ignored"
      | "rejected_unauthorized"
      | "rejected_invalid";
  },
) {
  return t.run((ctx) =>
    ctx.db.insert("publicationUpdates", {
      accountId: args.accountId,
      handle: args.handle,
      captureIds: args.captureIds,
      generation: args.generation,
      reportedState: "searchable",
      observedAt: Date.now(),
      receivedAt: Date.now(),
      outcome: args.outcome,
    }),
  );
}

async function insertServiceHealth(
  t: Awaited<ReturnType<typeof setup>>["t"],
  args: {
    service: "indexer" | "receiver" | "search";
    healthy: boolean;
    lastHeartbeatAt?: number;
    lastSuccessAt?: number;
    observedAt: number;
  },
) {
  return t.run((ctx) =>
    ctx.db.insert("serviceHealth", {
      service: args.service,
      healthy: args.healthy,
      lastHeartbeatAt: args.lastHeartbeatAt,
      lastSuccessAt: args.lastSuccessAt,
      observedAt: args.observedAt,
    }),
  );
}

describe("summary.summary", () => {
  it("reports known zeroes for an empty corpus (never omitted), and unknown only where nothing was ever reported", async () => {
    const { a } = await setup();
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.scope).toEqual({ kind: "global" });
    expect(result.indexedPosts).toEqual({ kind: "known", unit: "posts", value: 0 });
    expect(result.indexedAccounts).toEqual({ kind: "known", unit: "accounts", value: 0 });
    expect(result.queue).toEqual({
      waitingDownloads: { kind: "known", unit: "jobs", value: 0 },
      activeDownloads: { kind: "known", unit: "jobs", value: 0 },
      savedCapturesAwaitingIndexing: { kind: "known", unit: "captures", value: 0 },
      failedRetryable: { kind: "known", unit: "jobs", value: 0 },
    });
    // The one figure on an empty corpus that is honestly UNKNOWN rather than
    // a known zero: the four buckets above are things this app can check for
    // itself (it has no jobs, no receipts — a checked zero), whereas
    // providerQueuedWork only ever repeats what the indexer reported through
    // pendingWork. Nobody has reported anything, in any unit, so there is
    // nothing to state. "Unknown provider history size is 'unknown,' not
    // zero or an invented estimate" (to-do.md).
    expect(result.providerQueuedWork).toEqual({
      posts: { kind: "unknown", unit: "posts" },
      captures: { kind: "unknown", unit: "captures" },
      jobs: { kind: "unknown", unit: "jobs" },
    });
    expect(result.observedAt).toEqual(expect.any(Number));
  });

  it("requires authentication", async () => {
    const { t } = await setup();
    await expect(t.query(summaryQuery, { now: Date.now() })).rejects.toThrow();
  });

  it("echoes the caller-supplied `now` verbatim as observedAt instead of reading the wall clock, and `now` is a required arg", async () => {
    const { a } = await setup();
    // A value nowhere near the real wall clock: if this query read Date.now()
    // internally (the bug flagged against convex/_generated/ai/guidelines.md
    // "Do not read the wall clock inside a query"), observedAt could never
    // equal this. The `{ now: number }` FunctionReference type above (not
    // `{ now?: number }`) is itself a compile-time assertion that the arg is
    // required — an omitted `now` would fail `tsc --noEmit` on this file.
    const pinnedNow = 946_684_800_000; // 2000-01-01T00:00:00Z
    const result = await a.query(summaryQuery, { now: pinnedNow });
    expect(result.observedAt).toBe(pinnedNow);
  });

  it("sums searchablePostCount across accounts as the ONLY source for indexed posts", async () => {
    const { t, alice, a } = await setup();
    const one = await insertAccount(t, { handle: "one", userId: "1" });
    const two = await insertAccount(t, { handle: "two", userId: "2" });
    // Large, overlapping, unrelated raw counters that must never leak into
    // the total: jobs.count and jobs.postsReceived measure acquisition, not
    // the committed index.
    await insertJob(t, alice, { input: "one", expectedUserId: "1", count: 9_999 });
    await insertJob(t, alice, { input: "two", expectedUserId: "2" });
    await insertPublication(t, { accountId: one, state: "searchable", searchablePostCount: 100 });
    await insertPublication(t, { accountId: two, state: "searchable", searchablePostCount: 37 });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.indexedPosts).toEqual({ kind: "known", unit: "posts", value: 137 });
    expect(result.indexedAccounts).toEqual({ kind: "known", unit: "accounts", value: 2 });
  });

  it("returns unknown (never zero, never an estimate) when a searchable account never reported a unique post count", async () => {
    const { t, alice, a } = await setup();
    const known = await insertAccount(t, { handle: "known-one", userId: "1" });
    const unknownAcct = await insertAccount(t, { handle: "unknown-one", userId: "2" });
    await insertJob(t, alice, { input: "known-one", expectedUserId: "1" });
    await insertJob(t, alice, { input: "unknown-one", expectedUserId: "2" });
    await insertPublication(t, { accountId: known, state: "searchable", searchablePostCount: 42 });
    // Reported "searchable" but no uniquePostCount was ever accepted for it.
    await insertPublication(t, { accountId: unknownAcct, state: "searchable" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.indexedPosts).toEqual({ kind: "unknown", unit: "posts" });
    // indexedAccounts is a plain count of current state === "searchable",
    // which we CAN state honestly even though the post total is unknown.
    expect(result.indexedAccounts).toEqual({ kind: "known", unit: "accounts", value: 2 });
  });

  it("keeps a failed account's last committed post count in the total but out of the indexed-accounts count (non-regression)", async () => {
    const { t, alice, a } = await setup();
    const accountId = await insertAccount(t, { handle: "adam", userId: "1" });
    await insertJob(t, alice, { input: "adam", expectedUserId: "1", status: "failed" });
    await insertPublication(t, { accountId, state: "failed", searchablePostCount: 4_000 });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.indexedPosts).toEqual({ kind: "known", unit: "posts", value: 4_000 });
    expect(result.indexedAccounts).toEqual({ kind: "known", unit: "accounts", value: 0 });
  });

  it("treats an account that has never been searchable as a true zero, not unknown", async () => {
    const { t, alice, a } = await setup();
    const accountId = await insertAccount(t, { handle: "adam", userId: "1" });
    await insertJob(t, alice, { input: "adam", expectedUserId: "1" });
    await insertPublication(t, { accountId, state: "indexing" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.indexedPosts).toEqual({ kind: "known", unit: "posts", value: 0 });
    expect(result.indexedAccounts).toEqual({ kind: "known", unit: "accounts", value: 0 });
  });

  it("labels the four queue buckets with the right unit and never mislabels a count of files as a count of posts", async () => {
    const { t, alice, a } = await setup();
    await insertJob(t, alice, { input: "w1", status: "queued" });
    await insertJob(t, alice, { input: "r1", status: "running" });
    await insertJob(t, alice, { input: "f1", status: "failed" });
    await insertJob(t, alice, { input: "p1", status: "partial" });
    // Explicitly NOT retryable: a person's own cancellation is not a failure.
    await insertJob(t, alice, { input: "c1", status: "cancelled" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.queue.waitingDownloads).toEqual({ kind: "known", unit: "jobs", value: 1 });
    expect(result.queue.activeDownloads).toEqual({ kind: "known", unit: "jobs", value: 1 });
    expect(result.queue.failedRetryable).toEqual({ kind: "known", unit: "jobs", value: 2 });
    expect(result.queue.savedCapturesAwaitingIndexing.unit).toBe("captures");
  });

  it("counts a receipt as awaiting indexing until an accepted publication update confirms its captureId", async () => {
    const { t, alice, a } = await setup();
    const accountId = await insertAccount(t, { handle: "adam", userId: "1" });
    const job = await insertJob(t, alice, { input: "adam", expectedUserId: "1" });
    await insertReceipt(t, { jobId: job, captureId: "cap-1" });
    await insertReceipt(t, { jobId: job, captureId: "cap-2" });

    const before = await a.query(summaryQuery, { now: Date.now() });
    expect(before.queue.savedCapturesAwaitingIndexing).toEqual({
      kind: "known",
      unit: "captures",
      value: 2,
    });

    await insertPublicationUpdate(t, {
      accountId,
      handle: "adam",
      captureIds: ["cap-1"],
      generation: 1,
      outcome: "applied",
    });
    const afterOneConfirmed = await a.query(summaryQuery, { now: Date.now() });
    expect(afterOneConfirmed.queue.savedCapturesAwaitingIndexing).toEqual({
      kind: "known",
      unit: "captures",
      value: 1,
    });

    // A rejected/stale log entry must never count as confirming a capture.
    await insertPublicationUpdate(t, {
      accountId,
      handle: "adam",
      captureIds: ["cap-2"],
      generation: 0,
      outcome: "stale_ignored",
    });
    const afterStaleLog = await a.query(summaryQuery, { now: Date.now() });
    expect(afterStaleLog.queue.savedCapturesAwaitingIndexing).toEqual({
      kind: "known",
      unit: "captures",
      value: 1,
    });
  });

  it("excludes non-account job kinds (live/post/etc) from saved-captures-awaiting-indexing", async () => {
    const { t, alice, a } = await setup();
    const liveJob = await insertJob(t, alice, { kind: "live", input: "from:theo" });
    await insertReceipt(t, { jobId: liveJob, captureId: "cap-live" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.queue.savedCapturesAwaitingIndexing).toEqual({
      kind: "known",
      unit: "captures",
      value: 0,
    });
  });

  it("includes every owner's jobs in the queue — the queue is shared infrastructure, not one person's own", async () => {
    const { t, alice, bob, a } = await setup();
    await insertJob(t, alice, { input: "mine", status: "queued" });
    await insertJob(t, bob, { input: "theirs-1", status: "queued" });
    await insertJob(t, bob, { input: "theirs-2", status: "failed" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.queue.waitingDownloads).toEqual({ kind: "known", unit: "jobs", value: 2 });
    expect(result.queue.failedRetryable).toEqual({ kind: "known", unit: "jobs", value: 1 });
  });

  it("does not dedupe savedCapturesAwaitingIndexing per job — the same content-addressed captureId across two of one account's bulk jobs counts once, not twice", async () => {
    const { t, alice, a } = await setup();
    await insertAccount(t, { handle: "adam", userId: "1" });
    // Two separate bulk jobs for the SAME account (e.g. an original run plus
    // a retry) each produced a receipt for the SAME content-addressed
    // capture. Nothing has confirmed it yet.
    const job1 = await insertJob(t, alice, { input: "adam", expectedUserId: "1" });
    const job2 = await insertJob(t, alice, { input: "adam", expectedUserId: "1" });
    await insertReceipt(t, { jobId: job1, captureId: "shared-cap" });
    await insertReceipt(t, { jobId: job2, captureId: "shared-cap" });
    const result = await a.query(summaryQuery, { now: Date.now() });
    expect(result.queue.savedCapturesAwaitingIndexing).toEqual({
      kind: "known",
      unit: "captures",
      value: 1,
    });
  });

  it("counts indexedAccounts/indexedPosts across every owner's imports, and the tile always agrees with the account list it links to", async () => {
    const { t, alice, a, b } = await setup();
    const account = await insertAccount(t, { handle: "alice-account", userId: "1" });
    // Only alice ever ran a job for this account; bob has never imported
    // anything of his own.
    await insertJob(t, alice, { input: "alice-account", expectedUserId: "1" });
    await insertPublication(t, {
      accountId: account,
      state: "searchable",
      searchablePostCount: 10,
    });

    const bobsSummary = await b.query(summaryQuery, { now: Date.now() });
    const bobsLibrary = (await b.query(libraryRowsQuery, {})).rows;

    // The imported corpus is shared infrastructure, not personal data
    // (to-do.md, convex/lib/search.ts): bob reads the same GLOBAL
    // indexedAccounts/indexedPosts and the same account library as alice,
    // even though he never ran a job of his own. Both numbers are drawn
    // from the same account set library.rows uses, so the tile and the list
    // it links to agree by construction.
    expect(bobsSummary.scope).toEqual({ kind: "global" });
    expect(bobsSummary.indexedAccounts).toEqual({ kind: "known", unit: "accounts", value: 1 });
    expect(bobsSummary.indexedPosts).toEqual({ kind: "known", unit: "posts", value: 10 });
    expect(bobsLibrary).toHaveLength(1);
    expect(bobsLibrary[0].handle).toBe("alice-account");

    // Alice, who actually ran the job, sees the identical totals.
    const alicesSummary = await a.query(summaryQuery, { now: Date.now() });
    const alicesLibrary = (await a.query(libraryRowsQuery, {})).rows;
    expect(alicesSummary.indexedAccounts).toEqual(bobsSummary.indexedAccounts);
    expect(alicesSummary.indexedPosts).toEqual(bobsSummary.indexedPosts);
    expect(alicesLibrary).toHaveLength(1);
    expect(alicesLibrary[0].handle).toBe("alice-account");
    expect(alicesSummary.indexedAccounts).toEqual({
      kind: "known",
      unit: "accounts",
      value: alicesLibrary.filter((row) => row.publicationState === "searchable").length,
    });
  });
});

describe("summary.health", () => {
  it("reports unknown for a service that has never sent a health observation", async () => {
    const { a } = await setup();
    const result = await a.query(healthQuery, { now: Date.now() });
    expect(result).toEqual([
      { service: "indexer", kind: "unknown" },
      { service: "receiver", kind: "unknown" },
      { service: "search", kind: "unknown" },
    ]);
  });

  it("requires authentication", async () => {
    const { t } = await setup();
    await expect(t.query(healthQuery, { now: Date.now() })).rejects.toThrow();
  });

  it("distinguishes a stale observation from a live one, separately from configured", async () => {
    const { t, a } = await setup();
    const now = 1_000_000;
    await insertServiceHealth(t, {
      service: "indexer",
      healthy: true,
      lastHeartbeatAt: now - 10 * 60 * 1000, // 10 minutes old
      observedAt: now - 10 * 60 * 1000,
    });
    await insertServiceHealth(t, {
      service: "search",
      healthy: true,
      lastHeartbeatAt: now - 1_000,
      observedAt: now - 1_000,
    });
    const result = await a.query(healthQuery, { now });
    const byService = new Map(result.map((r) => [r.service, r]));
    expect(byService.get("indexer")).toMatchObject({ kind: "known", healthy: true, stale: true });
    expect(byService.get("search")).toMatchObject({ kind: "known", healthy: true, stale: false });
    // No observation at all is still distinguishable from either.
    expect(byService.get("receiver")).toEqual({ service: "receiver", kind: "unknown" });
  });

  it("reports a live known-unhealthy reading distinctly from stale or unknown", async () => {
    const { t, a } = await setup();
    const now = 2_000_000;
    await insertServiceHealth(t, {
      service: "receiver",
      healthy: false,
      lastHeartbeatAt: now - 500,
      observedAt: now - 500,
    });
    const result = await a.query(healthQuery, { now });
    const receiver = result.find((r) => r.service === "receiver");
    expect(receiver).toMatchObject({ kind: "known", healthy: false, stale: false });
  });
});
