import * as stylex from "@stylexjs/stylex";

// Class-based styles for the operator dashboard and account library
// (src/Dashboard.tsx, src/library/*). Ported 1:1 from src/dashboard.css.
// Dead rules with no tsx usage (`.control-caveats`) were dropped, not ported.
export const ops = stylex.create({
  room: {
    maxWidth: 1240,
    marginLeft: "auto",
    marginRight: "auto",
    paddingTop: 40,
    paddingBottom: 40,
    paddingLeft: 28,
    paddingRight: 28,
    color: "#eee",
    "@media (max-width: 760px)": {
      paddingTop: 24,
      paddingBottom: 24,
      paddingLeft: 18,
      paddingRight: 18,
    },
  },
  button: {
    backgroundColor: "transparent",
    border: "1px solid #444",
    color: "#eee",
    paddingTop: 9,
    paddingBottom: 9,
    paddingLeft: 13,
    paddingRight: 13,
    borderRadius: 6,
    fontSize: 13,
    cursor: "pointer",
    ":focus-visible": {
      outline: "2px solid #edb998",
      outlineOffset: 4,
    },
    ":disabled": {
      opacity: 0.4,
      cursor: "not-allowed",
    },
  },
  field: {
    width: "100%",
    border: "1px solid #3b3b3b",
    backgroundColor: "#171717",
    color: "#eee",
    padding: 12,
    borderRadius: 6,
    ":focus-visible": {
      outline: "2px solid #edb998",
      outlineOffset: 4,
    },
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
    alignItems: "center",
    marginBottom: 36,
    "@media (max-width: 760px)": {
      alignItems: "flex-start",
      flexWrap: "wrap",
    },
  },
  title: {
    fontSize: 42,
    letterSpacing: "-1.8px",
    marginTop: 24,
    marginBottom: 8,
    "@media (max-width: 760px)": {
      fontSize: 34,
    },
  },
  muted: {
    color: "#b3b3b3",
    fontSize: 13,
    lineHeight: 1.6,
    maxWidth: "68ch",
  },
  heading: {
    fontSize: 18,
    marginTop: 0,
    marginBottom: 20,
  },
  online: {
    color: "#a9d6b8",
    fontSize: 13,
    whiteSpace: "nowrap",
  },
  error: {
    color: "#ffaaa1",
    overflowWrap: "anywhere",
  },
  headerBadge: {
    whiteSpace: "nowrap",
    overflowWrap: "normal",
    flexShrink: 0,
    "@media (max-width: 760px)": {
      marginTop: 8,
    },
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "310px minmax(0, 1fr)",
    gap: 44,
    alignItems: "start",
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
      gap: 36,
    },
  },
  main: {
    display: "grid",
    gap: 40,
    minWidth: 0,
  },
  form: {
    display: "grid",
    gap: 16,
  },
  formLabel: {
    display: "grid",
    gap: 8,
    fontSize: 13,
  },
  check: {
    display: "flex",
    alignItems: "center",
  },
  checkbox: {
    width: "auto",
  },
  start: {
    backgroundColor: "#edb998",
    color: "#151515",
    borderColor: "#edb998",
    fontWeight: 600,
  },
  connections: {
    marginTop: 32,
    borderTop: "1px solid #333",
    paddingTop: 24,
  },
  connectionRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 13,
    paddingTop: 9,
    paddingBottom: 9,
    gap: 10,
  },
  connectionState: {
    color: "#bdbdbd",
  },
  job: {
    paddingTop: 24,
    paddingBottom: 24,
    borderTop: "1px solid #363636",
  },
  jobDismissed: {
    opacity: 0.55,
  },
  feedToggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 0,
    marginBottom: 8,
    color: "#a5a5a5",
    fontSize: 13,
  },
  jobHeading: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    "@media (max-width: 760px)": {
      alignItems: "flex-start",
    },
  },
  jobTitle: {
    fontSize: 20,
    overflowWrap: "anywhere",
    margin: 0,
  },
  jobText: {
    fontSize: 13,
    lineHeight: 1.6,
    color: "#bdbdbd",
    maxWidth: "68ch",
  },
  jobPhase: {
    color: "#eee",
  },
  jobStatus: {
    fontSize: 13,
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 9,
    paddingRight: 9,
    backgroundColor: "#292929",
    borderRadius: 4,
  },
  jobStatusRunning: {
    color: "#a9d6b8",
  },
  jobStatusComplete: {
    color: "#edb998",
  },
  jobStatusFailed: {
    color: "#ffaaa1",
  },
  warning: {
    borderLeft: "2px solid #776149",
    paddingLeft: 12,
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  receipts: {
    marginTop: 16,
    backgroundColor: "#191919",
    padding: 16,
    fontSize: 13,
    maxWidth: "80ch",
  },
  receipt: {
    marginBottom: 12,
  },
  receiptCode: {
    display: "block",
    overflowWrap: "anywhere",
    marginTop: 6,
    color: "#aaa",
  },
  empty: {
    paddingTop: 42,
    paddingBottom: 42,
    borderTop: "1px solid #333",
    maxWidth: 440,
  },
  feedNote: {
    marginTop: -8,
    marginBottom: 20,
  },
  // Account library (src/library/*).
  library: {
    maxWidth: 1240,
    marginLeft: "auto",
    marginRight: "auto",
    paddingTop: 32,
    paddingBottom: 32,
    paddingLeft: 28,
    paddingRight: 28,
    color: "#eee",
    display: "grid",
    gap: 36,
    "@media (max-width: 760px)": {
      paddingTop: 20,
      paddingBottom: 20,
      paddingLeft: 16,
      paddingRight: 16,
      gap: 28,
    },
  },
  offlineBanner: {
    border: "1px solid #776149",
    borderRadius: 8,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 14,
    paddingRight: 14,
    fontSize: 13,
    color: "#edb998",
    backgroundColor: "rgba(237, 185, 152, 0.08)",
  },
  section: {
    display: "grid",
    gap: 14,
  },
  sectionTitle: {
    fontSize: 18,
    margin: 0,
  },
  subhead: {
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#9c9c9c",
    marginTop: 0,
    marginBottom: 10,
  },
  sectionHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 12,
    flexWrap: "wrap",
  },
  libraryMuted: {
    color: "#b3b3b3",
    fontSize: 13,
    lineHeight: 1.6,
    margin: 0,
    maxWidth: "68ch",
  },
  loading: {
    paddingTop: 20,
    paddingBottom: 20,
    color: "#bdbdbd",
    fontSize: 13,
    lineHeight: 1.6,
  },
  emptyBox: {
    paddingTop: 20,
    paddingBottom: 20,
    color: "#bdbdbd",
    fontSize: 13,
    lineHeight: 1.6,
  },
  emptyBoxButton: {
    marginTop: 10,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 12,
    "@media (max-width: 760px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  stat: {
    backgroundColor: "#171717",
    border: "1px solid #2c2c2c",
    borderRadius: 10,
    padding: 16,
    display: "grid",
    gap: 6,
  },
  statValue: {
    fontSize: 28,
    fontWeight: 600,
    letterSpacing: "-0.5px",
  },
  statValueUnknown: {
    color: "#8a8a8a",
    fontSize: 18,
    fontWeight: 500,
    fontStyle: "italic",
  },
  statLabel: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#9c9c9c",
  },
  statSub: {
    fontSize: 12,
    color: "#8a8a8a",
  },
  statCaveat: {
    fontSize: 11,
    lineHeight: 1.5,
    color: "#8a8a8a",
    fontStyle: "italic",
  },
  statLink: {
    textDecoration: "none",
    color: "inherit",
    cursor: "pointer",
    ":hover": {
      borderColor: "#565656",
    },
    ":focus-visible": {
      borderColor: "#565656",
      outline: "2px solid #9ecbff",
      outlineOffset: 2,
    },
  },
  statLinkLabel: {
    textDecoration: "underline",
    textDecorationColor: "#565656",
    textUnderlineOffset: 3,
  },
  healthRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 999,
    backgroundColor: "#232323",
    color: "#cfcfcf",
    whiteSpace: "nowrap",
  },
  badgePositive: {
    color: "#a9d6b8",
    backgroundColor: "rgba(169, 214, 184, 0.12)",
  },
  badgeInfo: {
    color: "#9ecbff",
    backgroundColor: "rgba(158, 203, 255, 0.12)",
  },
  badgeWarning: {
    color: "#edb998",
    backgroundColor: "rgba(237, 185, 152, 0.12)",
  },
  badgeDanger: {
    color: "#ffaaa1",
    backgroundColor: "rgba(255, 170, 161, 0.12)",
  },
  queueList: {
    display: "grid",
    gap: 8,
  },
  queueRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#171717",
    border: "1px solid #2c2c2c",
    borderRadius: 8,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 14,
    paddingRight: 14,
    fontSize: 13,
    flexWrap: "wrap",
  },
  queueIdentity: {
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  queueStalled: {
    color: "#edb998",
  },
  controls: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    alignItems: "center",
    "@media (max-width: 760px)": {
      flexDirection: "column",
      alignItems: "stretch",
    },
  },
  controlsField: {
    backgroundColor: "#171717",
    border: "1px solid #3b3b3b",
    color: "#eee",
    paddingTop: 9,
    paddingBottom: 9,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 6,
  },
  controlsSearch: {
    flex: 1,
    minWidth: 200,
    "@media (max-width: 760px)": {
      minWidth: 0,
    },
  },
  rows: {
    display: "grid",
    gap: 10,
  },
  row: {
    backgroundColor: "#171717",
    border: "1px solid #2c2c2c",
    borderRadius: 10,
    paddingTop: 18,
    paddingBottom: 18,
    paddingLeft: 20,
    paddingRight: 20,
    display: "grid",
    gap: 10,
  },
  rowHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
    "@media (max-width: 760px)": {
      alignItems: "flex-start",
    },
  },
  identity: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  avatar: {
    objectFit: "cover",
    backgroundColor: "#2b2b2b",
    width: 36,
    height: 36,
    borderRadius: "50%",
    flexShrink: 0,
  },
  avatarFallback: {
    backgroundColor: "#2b2b2b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    color: "#9c9c9c",
    width: 36,
    height: 36,
    borderRadius: "50%",
    flexShrink: 0,
  },
  identityText: {
    minWidth: 0,
  },
  identityName: {
    margin: 0,
    fontSize: 16,
    overflowWrap: "anywhere",
  },
  identityHandle: {
    fontSize: 12,
    color: "#9c9c9c",
  },
  rowBadges: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    alignItems: "center",
  },
  rowMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px 18px",
    fontSize: 13,
    color: "#bdbdbd",
  },
  rowMetaStrong: {
    color: "#eee",
    fontWeight: 600,
  },
  rowNote: {
    fontSize: 13,
    color: "#a9d6b8",
    margin: 0,
    maxWidth: "68ch",
  },
  rowFailure: {
    borderLeft: "2px solid #776149",
    paddingLeft: 12,
    fontSize: 13,
    color: "#ffaaa1",
    overflowWrap: "anywhere",
    margin: 0,
  },
  rowActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  rowToggle: {
    marginLeft: "auto",
    "@media (max-width: 760px)": {
      marginLeft: 0,
    },
  },
  history: {
    borderTop: "1px solid #2c2c2c",
    paddingTop: 12,
    display: "grid",
    gap: 12,
  },
  historyRun: {
    display: "grid",
    gap: 4,
    fontSize: 13,
  },
  historyRunHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  historyRunText: {
    margin: 0,
    color: "#cfcfcf",
  },
  rawDetailsSummary: {
    cursor: "pointer",
    color: "#9c9c9c",
    fontSize: 12,
  },
  historyReceipts: {
    marginTop: 6,
    fontSize: 12,
    color: "#aaa",
    display: "grid",
    gap: 6,
  },
  historyReceiptCode: {
    overflowWrap: "anywhere",
  },
});
