import * as stylex from "@stylexjs/stylex";

// Class-based styles for the public site (src/App.tsx, src/main.tsx,
// src/operator/Connections.tsx). Ported 1:1 from src/style.css; element
// defaults, :root tokens, keyframes, and dialog::backdrop stay in
// src/global.css, which StyleX cannot express.
export const site = stylex.create({
  app: {
    minHeight: "100svh",
    display: "flex",
    flexDirection: "column",
  },
  topbar: {
    height: 92,
    paddingLeft: "5%",
    paddingRight: "5%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    "@media (max-width: 700px)": {
      height: 75,
      paddingLeft: 20,
      paddingRight: 20,
    },
  },
  wordmark: {
    fontSize: 27,
    fontWeight: 700,
    letterSpacing: "-1.5px",
    padding: 0,
    borderWidth: 0,
    "@media (max-width: 700px)": {
      fontSize: 24,
    },
  },
  wordmarkDot: {
    color: "var(--accent)",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: 18,
    "@media (max-width: 700px)": {
      gap: 4,
    },
  },
  navButton: {
    fontSize: 13,
    borderColor: "transparent",
    color: "#bdbab5",
    padding: 8,
    "@media (max-width: 700px)": {
      minWidth: 36,
      minHeight: 36,
    },
  },
  navButtonPressed: {
    color: "var(--accent)",
    backgroundColor: "#1d1712",
  },
  importNav: {
    borderColor: "#393530",
    color: "#e9e7e3",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 14,
    paddingRight: 14,
    "@media (max-width: 700px)": {
      padding: 8,
    },
  },
  navButtonLabel: {
    "@media (max-width: 700px)": {
      display: "none",
    },
  },
  navCount: {
    color: "var(--accent)",
  },
  connection: {
    maxWidth: "calc(100% - 40px)",
    marginTop: 16,
    marginBottom: 16,
    marginLeft: "auto",
    marginRight: "auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    fontSize: 13,
    color: "#d9b797",
    backgroundColor: "#18130f",
    border: "1px solid #473426",
    paddingTop: 9,
    paddingBottom: 9,
    paddingLeft: 13,
    paddingRight: 13,
    borderRadius: 5,
    width: "max-content",
    "@media (max-width: 700px)": {
      marginTop: 8,
    },
  },
  connectionDot: {
    width: 6,
    height: 6,
    flexShrink: 0,
    flexGrow: 0,
    flexBasis: "auto",
    borderRadius: "50%",
    backgroundColor: "var(--accent)",
    boxShadow: "0 0 0 4px rgb(255 201 155 / 10%)",
    "@media (prefers-reduced-motion: no-preference)": {
      animationName: "status-pulse",
      animationDuration: "1.8s",
      animationTimingFunction: "ease-in-out",
      animationIterationCount: "infinite",
    },
  },
  searchStage: {
    position: "relative",
    maxWidth: 1120,
    marginTop: 30,
    marginLeft: "auto",
    marginRight: "auto",
    paddingLeft: 28,
    paddingRight: 28,
    "@media (max-width: 700px)": {
      paddingLeft: 20,
      paddingRight: 20,
      marginTop: 20,
    },
  },
  searchStageHome: {
    minHeight: 560,
    height: "calc(100svh - 220px)",
    maxHeight: 760,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 20,
    "@media (min-width: 1400px)": {
      minHeight: 640,
    },
    "@media (max-width: 1100px)": {
      maxHeight: 650,
    },
    "@media (max-width: 700px)": {
      minHeight: 460,
      height: "calc(100svh - 190px)",
      paddingTop: 30,
      paddingBottom: 30,
      paddingLeft: 20,
      paddingRight: 20,
    },
  },
  searchStageResults: {
    maxWidth: 1100,
    marginTop: 24,
    "@media (max-width: 700px)": {
      paddingLeft: 20,
      paddingRight: 20,
      marginTop: 20,
    },
  },
  orbit: {
    position: "absolute",
    top: -8,
    bottom: 0,
    left: 0,
    right: 0,
    pointerEvents: "none",
    "@media (max-width: 1100px)": {
      top: 0,
      left: 15,
      right: 15,
    },
    "@media (max-width: 700px)": {
      display: "none",
    },
  },
  orbitButton: {
    position: "absolute",
    transform: "translate(-50%, -50%)",
    borderWidth: 0,
    borderRadius: "50%",
    padding: 0,
    pointerEvents: "auto",
    boxShadow: "0 6px 20px #000",
    "@media (prefers-reduced-motion: no-preference)": {
      ":hover": {
        transform: "translate(-50%, -50%) scale(1.1)",
      },
    },
  },
  heroTitle: {
    position: "relative",
    zIndex: 1,
    textAlign: "center",
    marginBottom: 36,
    "@media (min-width: 1400px)": {
      marginBottom: 40,
    },
    "@media (max-width: 700px)": {
      marginBottom: 28,
    },
  },
  heroKicker: {
    color: "#aca8a2",
    fontSize: 12,
    letterSpacing: "0.3px",
    marginBottom: 12,
  },
  heroHeading: {
    fontSize: 42,
    fontWeight: 500,
    letterSpacing: "-1.8px",
    margin: 0,
    "@media (min-width: 1400px)": {
      fontSize: 48,
    },
    "@media (max-width: 700px)": {
      fontSize: 35,
    },
  },
  searchForm: {
    position: "relative",
    width: "100%",
    maxWidth: 850,
    zIndex: 2,
  },
  searchFormResults: {
    maxWidth: "100%",
  },
  searchFormHome: {
    "@media (max-width: 1100px)": {
      maxWidth: 740,
    },
  },
  searchLabel: {
    display: "block",
    color: "#b9b6b1",
    fontSize: 13,
    marginBottom: 10,
  },
  searchControls: {
    display: "grid",
    gridTemplateColumns: "minmax(160px, 1fr) 200px 110px",
    gap: 8,
    "@media (min-width: 1400px)": {
      gridTemplateColumns: "minmax(160px, 1fr) 200px 116px",
    },
    "@media (max-width: 700px)": {
      gridTemplateColumns: "1fr 100px",
    },
  },
  queryWrap: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    "@media (max-width: 700px)": {
      gridColumn: "1/-1",
    },
  },
  queryIcon: {
    position: "absolute",
    left: 16,
    color: "#7f7c78",
    pointerEvents: "none",
  },
  queryInput: {
    width: "100%",
    height: 52,
    paddingLeft: 46,
    "@media (min-width: 1400px)": {
      height: 55,
    },
  },
  searchSelect: {
    "@media (max-width: 700px)": {
      height: 46,
      fontSize: 13,
    },
  },
  primary: {
    backgroundColor: "var(--accent)",
    borderColor: "var(--accent)",
    color: "#1a110b",
    fontWeight: 600,
    ":hover:not(:disabled)": {
      backgroundColor: "#ffdbb9",
      borderColor: "#ffdbb9",
    },
  },
  searchHelp: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    color: "#a8a5a0",
    fontSize: 12,
    marginTop: 12,
    "@media (max-width: 700px)": {
      display: "block",
      fontSize: 11,
      lineHeight: 1.7,
    },
  },
  searchHelpAt: {
    color: "var(--accent)",
    fontWeight: 500,
  },
  statsToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    color: "#c8c3bc",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  statsCheckbox: {
    accentColor: "var(--accent)",
  },
  textButton: {
    borderWidth: 0,
    padding: 0,
    fontSize: 13,
    color: "var(--accent)",
    borderRadius: 0,
  },
  aiButton: {
    whiteSpace: "nowrap",
    "@media (max-width: 700px)": {
      marginTop: 10,
    },
  },
  proposal: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    zIndex: 3,
    maxWidth: 850,
    width: "100%",
    padding: 15,
    backgroundColor: "#201a15",
    border: "1px solid #443426",
    marginTop: 16,
    fontSize: 13,
    "@media (max-width: 700px)": {
      flexDirection: "column",
      alignItems: "flex-start",
    },
  },
  proposalText: {
    fontSize: 12,
    color: "#b1a08d",
    marginTop: 7,
    marginBottom: 0,
  },
  proposalButton: {
    whiteSpace: "nowrap",
  },
  libraryStatus: {
    marginTop: 35,
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    color: "var(--muted)",
    fontSize: 13,
    zIndex: 1,
    "@media (max-width: 700px)": {
      fontSize: 11,
      flexWrap: "wrap",
      marginTop: 28,
    },
  },
  statusDot: {
    height: 5,
    width: 5,
    backgroundColor: "#a8c69a",
    borderRadius: "50%",
  },
  statusDotMuted: {
    backgroundColor: "#6c6258",
  },
  statusDotLoading: {
    backgroundColor: "var(--accent)",
    "@media (prefers-reduced-motion: no-preference)": {
      animationName: "status-pulse",
      animationDuration: "1.8s",
      animationTimingFunction: "ease-in-out",
      animationIterationCount: "infinite",
    },
  },
  libraryStatusButton: {
    marginLeft: 5,
  },
  notice: {
    maxWidth: 1044,
    marginTop: 16,
    marginBottom: 16,
    marginLeft: "auto",
    marginRight: "auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    fontSize: 13,
    backgroundColor: "#201a15",
    color: "#edc59f",
    border: "1px solid #473426",
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 5,
    "@media (max-width: 1100px)": {
      marginLeft: 28,
      marginRight: 28,
    },
    "@media (max-width: 700px)": {
      marginLeft: 20,
      marginRight: 20,
    },
  },
  iconButton: {
    padding: 7,
    borderColor: "transparent",
    flexShrink: 0,
  },
  empty: {
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    paddingTop: 65,
    paddingBottom: 80,
    paddingLeft: 20,
    paddingRight: 20,
    color: "#a29e98",
  },
  emptySmall: {
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 10,
    paddingRight: 10,
  },
  emptyIcon: {
    color: "#bda58a",
    marginBottom: 20,
  },
  emptyText: {
    fontSize: 13,
    maxWidth: "46ch",
  },
  modalInner: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "calc(100svh - 50px)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 15,
    flexShrink: 0,
    paddingTop: 28,
    paddingBottom: 18,
    paddingLeft: 28,
    paddingRight: 28,
    "@media (max-width: 700px)": {
      paddingTop: 22,
      paddingBottom: 16,
      paddingLeft: 22,
      paddingRight: 22,
    },
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 500,
    letterSpacing: "-0.6px",
    margin: 0,
  },
  modalBody: {
    overflowY: "auto",
    minHeight: 0,
    paddingTop: 0,
    paddingBottom: 28,
    paddingLeft: 28,
    paddingRight: 28,
    "@media (max-width: 700px)": {
      paddingTop: 0,
      paddingBottom: 22,
      paddingLeft: 22,
      paddingRight: 22,
    },
  },
  mutedCopy: {
    fontSize: 12,
    color: "#b0a99f",
  },
  stackForm: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginTop: 24,
    marginBottom: 24,
  },
  stackLabel: {
    fontSize: 12,
  },
  stackLabelNote: {
    color: "var(--muted)",
    marginLeft: 6,
  },
  stackSubmit: {
    marginTop: 8,
  },
  stackTextButton: {
    alignSelf: "flex-start",
  },
  configWarning: {
    fontSize: 12,
    color: "#e3b187",
  },
  jobs: {
    marginTop: 30,
  },
  jobsHeading: {
    fontSize: 14,
    fontWeight: 500,
  },
  job: {
    paddingTop: 15,
    paddingBottom: 15,
    borderTop: "1px solid var(--line)",
  },
  jobRow: {
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    alignItems: "center",
  },
  jobTitle: {
    fontWeight: 500,
    fontSize: 13,
    overflowWrap: "anywhere",
  },
  jobStatus: {
    fontSize: 10,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 7,
    paddingRight: 7,
    backgroundColor: "#27211a",
    color: "#d7b28b",
    borderRadius: 4,
  },
  jobStatusComplete: {
    color: "#b4c49d",
    backgroundColor: "#20251b",
  },
  jobStatusFailed: {
    color: "#e3a99e",
    backgroundColor: "#33231f",
  },
  jobText: {
    fontSize: 12,
    color: "#b3aca2",
    marginTop: 8,
    marginBottom: 8,
  },
  jobButton: {
    fontSize: 11,
    marginTop: 6,
  },
  savedRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    borderTop: "1px solid var(--line)",
    paddingTop: 8,
    paddingBottom: 8,
  },
  savedRowOpen: {
    borderWidth: 0,
    fontSize: 13,
    textAlign: "left",
    justifyContent: "flex-start",
    overflowWrap: "anywhere",
  },
  delivery: {
    fontSize: 12,
    marginTop: 12,
  },
  pageText: {
    whiteSpace: "pre-wrap",
    fontSize: 14,
    lineHeight: 1.8,
    overflowWrap: "anywhere",
    marginTop: 24,
  },
  pageBlock: {
    marginTop: 0,
    marginBottom: 0,
  },
  sourceLink: {
    fontSize: 12,
    color: "var(--accent)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  siteFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 28,
    paddingBottom: 28,
    paddingLeft: "5%",
    paddingRight: "5%",
    color: "var(--muted)",
    fontSize: 12,
    "@media (max-width: 700px)": {
      paddingTop: 22,
      paddingBottom: 22,
      paddingLeft: 20,
      paddingRight: 20,
      fontSize: 10,
      gap: 16,
    },
  },
  siteFooterTagline: {
    "@media (max-width: 700px)": {
      display: "none",
    },
  },
  siteFooterLinks: {
    display: "flex",
    gap: 22,
    alignItems: "center",
    "@media (max-width: 700px)": {
      width: "100%",
      justifyContent: "space-between",
    },
  },
  siteFooterLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  },
  siteFooterButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    borderWidth: 0,
    padding: 0,
    color: "inherit",
  },
  setup: {
    maxWidth: 600,
    marginTop: "18vh",
    marginLeft: "auto",
    marginRight: "auto",
    padding: 25,
  },
  setupText: {
    color: "var(--muted)",
  },
  // Operator Connections panel (src/operator/Connections.tsx).
  connectionRow: {
    paddingTop: 18,
    paddingBottom: 18,
    borderTop: "1px solid var(--line)",
  },
  connectionRowTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  connectionRowName: {
    fontSize: 14,
    fontWeight: 500,
  },
  connectionRowText: {
    fontSize: 12,
    color: "#b3a99d",
    marginTop: 8,
    marginBottom: 8,
  },
});
